/* =========================================================================
   PoE_PatchNotes — treść (hardcoded)
   Źródło: https://www.pathofexile.com/forum/view-thread/3985332/page/1
   Każda linia: { d: głębokość wcięcia, b: podnagłówek?, en: oryginał, pl: tłumaczenie }
   Nazwy własne PoE (przedmioty, gemy, mechaniki) pozostają po angielsku;
   tłumaczenie pomocnicze bywa podane w nawiasie.
   ========================================================================= */
window.PATCH_DATA = {
  meta: {
    version: "3.29.0",
    titleEn: "Content Update 3.29.0 — Path of Exile: Curse of the Allflame",
    titlePl: "Aktualizacja 3.29.0 — Path of Exile: Curse of the Allflame",
    source: "https://www.pathofexile.com/forum/view-thread/3985332/page/1",
    updated: "2026-07-17"
  },
  sections: []
};
function PN(s) { window.PATCH_DATA.sections.push(s); }
PN({ id: "the-curse-of-the-allflame-challenge-league", title: { pl: "Liga wyzwań: The Curse of the Allflame", en: "The Curse of the Allflame Challenge League" }, lines: [
  { d:0, b:false, en:"Meet Valerie, a dangerous corsair captain who needs your help retrieving long forgotten treasures from the icy depths of Wraeclast's oceans. Find Charts scattered across Wraeclast, board The Sovereign, and set sail!", pl:"Poznaj Valerie, niebezpieczną kapitan korsarzy, która potrzebuje twojej pomocy w wydobyciu dawno zapomnianych skarbów z lodowatych głębin oceanów Wraeclast. Odnajduj Charts (mapy morskie) rozsiane po całym Wraeclast, wejdź na pokład The Sovereign i wypłyń w morze!" },
  { d:0, b:false, en:"Dive to the ocean floor where lanterns imbued with the spark of the Allflame will shield you from the crushing waves. Explore and claim what you can while you can! Lost gold, valuable chests, and lurking threats await you...", pl:"Zanurkuj na dno oceanu, gdzie latarnie przepełnione iskrą Allflame osłonią cię przed miażdżącymi falami. Eksploruj i zgarniaj, co się da, póki możesz! Czekają na ciebie zagubione złoto, cenne skrzynie i czające się zagrożenia..." },
  { d:0, b:false, en:"Upon charting enough areas, connect them together to create a Voyage — one giant seafloor excursion. Revisit each chart to claim its rewards again, while also amplifying those rewards in several different ways.", pl:"Gdy naniesiesz na mapę wystarczająco wiele obszarów, połącz je w Voyage (rejs) — jedną wielką wyprawę po dnie morskim. Odwiedzaj ponownie każdą Chart, by znów zgarnąć jej nagrody, jednocześnie zwiększając je na kilka różnych sposobów." },
  { d:0, b:false, en:"Head belowdecks, and you'll find the heart of the ship at work. Feed it an item, and it will split into a multitude of ghostly outcomes, one of which you can keep for yourself.", pl:"Zejdź pod pokład, a zastaniesz przy pracy serce statku (heart of the ship). Nakarm je przedmiotem, a rozdzieli się on na mnóstwo widmowych wariantów, z których jeden możesz zatrzymać dla siebie." },
  { d:0, b:false, en:"Find valuable Ducats on the seafloor and use them to warp and twist items in ways not seen in centuries.", pl:"Znajduj cenne Ducats (dukaty) na dnie morza i używaj ich, by wypaczać i przekształcać przedmioty w sposób niewidziany od stuleci." },
  { d:0, b:false, en:"For more information about this expansion, check out pathofexile.com/allflame", pl:"Więcej informacji o tym dodatku znajdziesz na pathofexile.com/allflame" },
  { d:0, b:false, en:"With 3.29.0, there are Standard, Hardcore and Solo Self-Found variations of the Curse of the Allflame challenge league available. They have the same core mechanics and items. You can create private league versions of these leagues, with mods that make the game harder.", pl:"Wraz z 3.29.0 dostępne są warianty Standard, Hardcore oraz Solo Self-Found ligi wyzwań Curse of the Allflame. Mają one te same podstawowe mechaniki i przedmioty. Możesz tworzyć prywatne wersje tych lig, z modyfikatorami utrudniającymi grę." },
  { d:0, b:false, en:"The Hardcore variations of Curse of the Allflame are parented to their Standard Curse of the Allflame equivalent, meaning if you die in Hardcore Curse of the Allflame you can continue on in the Standard Curse of the Alfflame League.", pl:"Warianty Hardcore ligi Curse of the Allflame są podpięte pod swój odpowiednik Standard, co oznacza, że jeśli zginiesz w Hardcore Curse of the Allflame, możesz kontynuować grę w lidze Standard Curse of the Allflame." },
  { d:0, b:false, en:"The new Curse of the Allflame challenge league includes a set of 40 new challenges, and 8 new challenges in Ruthless Curse of the Allflame. There are microtransaction rewards for completing challenges that are only obtainable in this league. These rewards will be revealed in an upcoming news post.", pl:"Nowa liga wyzwań Curse of the Allflame zawiera zestaw 40 nowych wyzwań (challenges) oraz 8 nowych wyzwań w Ruthless Curse of the Allflame. Za ukończenie wyzwań przewidziano nagrody-mikrotransakcje dostępne wyłącznie w tej lidze. Nagrody te zostaną ujawnione w nadchodzącym wpisie z aktualnościami." },
  { d:0, b:false, en:"From the 19th challenge onwards and for every third challenge after that, you will receive pieces of the Curse of the Allflame Totem Pole decoration to display in your hideout. The Totem Pole permanently showcases how many of the Curse of the Allflame challenges you completed during the league.", pl:"Począwszy od 19. wyzwania oraz za każde trzecie wyzwanie po nim otrzymasz części dekoracji Curse of the Allflame Totem Pole (pala totemicznego) do umieszczenia w swoim hideout (kryjówce). Totem Pole na stałe prezentuje, ile wyzwań Curse of the Allflame ukończyłeś w trakcie ligi." }
]});

PN({ id: "new-content-and-features", title: { pl: "Nowa zawartość i funkcje", en: "New Content and Features" }, lines: [
  { d:0, b:false, en:"Introduced two new Bloodline Classes, one which is exclusive to the Curse of the Allflame challenge league.", pl:"Wprowadzono dwie nowe klasy Bloodline (rodowe), z których jedna jest dostępna wyłącznie w lidze wyzwań Curse of the Allflame." },
  { d:0, b:false, en:"Added a new Exceptional Skill Gem, Pact of Beidat: Cast a pact, Empowering spells that either fire projectiles, apply an effect to an area around a targeted location or fire chaining beams, causing them deal more damage and have enhanced coverage. However, using this skill also burdens you with an Affliction.", pl:"Dodano nowy Exceptional Skill Gem (wyjątkowy klejnot umiejętności), Pact of Beidat: Rzuca pakt, wzmacniając (Empower) zaklęcia, które wystrzeliwują pociski, nakładają efekt na obszar wokół wskazanego miejsca lub wystrzeliwują łańcuchujące wiązki — sprawiając, że zadają więcej obrażeń i mają zwiększony zasięg. Użycie tej umiejętności obarcza cię jednak Affliction (przypadłością)." },
  { d:0, b:false, en:"Added a new Exceptional Skill Gem, Pact of Ghorr: Cast a pact, Empowering your damage over time spells but burdening you with an Affliction. This skill also grants the Hunger of Ghorr buff for a duration causing Fleshrend to trigger periodically.", pl:"Dodano nowy Exceptional Skill Gem, Pact of Ghorr: Rzuca pakt, wzmacniając twoje zaklęcia zadające obrażenia w czasie (damage over time), lecz obarczając cię Affliction. Umiejętność ta nadaje też na pewien czas buff Hunger of Ghorr, sprawiając, że okresowo wyzwala się Fleshrend." },
  { d:0, b:false, en:"Added a new Exceptional Skill Gem, Pact of K'tash: Cast a pact, Empowering your damaging Vaal spells but burdening you with an Affliction. Empowered Vaal spells deal more damage, have less soul gain prevention duration and refund souls on use.", pl:"Dodano nowy Exceptional Skill Gem, Pact of K'tash: Rzuca pakt, wzmacniając twoje zadające obrażenia zaklęcia Vaal, lecz obarczając cię Affliction. Wzmocnione zaklęcia Vaal zadają więcej obrażeń, mają krótszy czas blokady pozyskiwania dusz (soul gain prevention) i zwracają dusze przy użyciu." },
  { d:0, b:false, en:"Added a new Exceptional Skill Gem, Pact of Lycia: Cast a pact, Empowering the next channelling spells you cast yourself but burdening you with an Affliction. Empowered spells deal more damage and periodically trigger lightning bolts while channelling.", pl:"Dodano nowy Exceptional Skill Gem, Pact of Lycia: Rzuca pakt, wzmacniając kolejne kanałowane (channelling) zaklęcia, które sam rzucisz, lecz obarczając cię Affliction. Wzmocnione zaklęcia zadają więcej obrażeń i okresowo wyzwalają błyskawice podczas kanałowania." },
  { d:0, b:false, en:"Added a new Exceptional Support Gem, Coursing Currents: Supports skills that hit enemies, providing increased effect of Chill and Shock inflicted with Supported Skills, causing enemies to be chilled when they are shocked by your hits, and shocked when they are chilled by your hits.", pl:"Dodano nowy Exceptional Support Gem (wyjątkowy klejnot wspierający), Coursing Currents: Wspiera umiejętności trafiające wrogów, zwiększając efekt Chill (schłodzenia) i Shock (porażenia) nakładanych wspieranymi umiejętnościami oraz sprawiając, że wrogowie zostają schłodzeni, gdy porazisz ich trafieniami, i porażeni, gdy schłodzisz ich trafieniami." },
  { d:0, b:false, en:"Added a new Exceptional Support Gem, Crystalfall: Supported Skills will Trigger Falling Crystal on Hit, causing a giant crystal of abyssal soulstone to be called from above, falling to slam down at the targeted location. Supports Slam skills. Cannot support triggered skills or skills used by things other than you.", pl:"Dodano nowy Exceptional Support Gem, Crystalfall: Wspierane umiejętności wyzwalają Falling Crystal (spadający kryształ) przy trafieniu, przywołując z góry gigantyczny kryształ abyssal soulstone, który spada, uderzając we wskazane miejsce. Wspiera umiejętności typu Slam. Nie może wspierać umiejętności wyzwalanych ani używanych przez cokolwiek innego niż ty." },
  { d:0, b:false, en:"Added a new Intelligence/Strength Skill, Mana-Infused Staff: Infuses your staff with arcane energy, lowering your mana costs and increasing your chance to block. When you block, you release an arcane wave, damaging enemies in a ring-shaped area over a duration.", pl:"Dodano nową umiejętność Intelligence/Strength, Mana-Infused Staff: Przesyca twój staff (kostur) energią arkany, obniżając koszty many i zwiększając szansę na blok. Gdy blokujesz, uwalniasz falę arkany, zadającą wrogom obrażenia w obszarze w kształcie pierścienia przez pewien czas." },
  { d:0, b:false, en:"Added a new Strength/Intelligence Transfigured Skill, Divine Blast of Radiance: Project a beam of holy light from your shield to a targeted location, causing an implosion of holy energy. This energy then lingers for a short duration as an orb, periodically releasing larger explosions. Increases and reductions to attack speed affect the rate at which explosions occur.", pl:"Dodano nową umiejętność Transfigured (przekształconą) Strength/Intelligence, Divine Blast of Radiance: Wystrzeliwuje wiązkę świętego światła z twojej tarczy we wskazane miejsce, wywołując implozję świętej energii. Energia ta utrzymuje się następnie przez krótki czas jako kula, okresowo uwalniając większe eksplozje. Zwiększenia i zmniejszenia attack speed (szybkości ataku) wpływają na tempo występowania eksplozji." },
  { d:0, b:false, en:"Added a new Strength/Intelligence Transfigured Skill, Holy Hammers of Spirals: Slam the ground, consuming all Power Charges and calling down a cascade of holy hammers from above in an outward spiral. Further hammers are called down for each Power Charge consumed. Requires a Mace, Sceptre or Staff.", pl:"Dodano nową umiejętność Transfigured Strength/Intelligence, Holy Hammers of Spirals: Uderza w ziemię, zużywając wszystkie Power Charges (ładunki mocy) i sprowadzając z góry kaskadę świętych młotów w rozchodzącej się spirali. Za każdy zużyty Power Charge sprowadzanych jest więcej młotów. Wymaga broni Mace, Sceptre lub Staff." },
  { d:0, b:false, en:"Added a new Strength/Intelligence Transfigured Skill, Holy Sweep of Hammerfalls: Swings a two handed mace or a staff in a circle, calling down waves of holy hammers for a duration. Increases and reductions to Attack Speed will affect the rate at which these hammerfalls occur.", pl:"Dodano nową umiejętność Transfigured Strength/Intelligence, Holy Sweep of Hammerfalls: Wykonuje zamach dwuręcznym maczugą (two handed mace) lub kosturem (staff) w okręgu, sprowadzając fale świętych młotów przez pewien czas. Zwiększenia i zmniejszenia Attack Speed wpływają na tempo, w jakim występują te uderzenia młotów." },
  { d:0, b:false, en:"Added a new Strength/Intelligence Transfigured Skill, Reap of Butchery: A bloody scythe swipes around you, applying a physical damage over time debuff and hitting enemies with physical damage. If any survive, you gain a blood charge which raises the damage and cost of the skill. Players can have 5 maximum blood charges.", pl:"Dodano nową umiejętność Transfigured Strength/Intelligence, Reap of Butchery: Krwawa kosa tnie wokół ciebie, nakładając debuff fizycznych obrażeń w czasie (physical damage over time) i trafiając wrogów obrażeniami fizycznymi. Jeśli ktokolwiek przeżyje, zyskujesz blood charge (ładunek krwi), który zwiększa obrażenia i koszt umiejętności. Gracze mogą mieć maksymalnie 5 blood charges." },
  { d:0, b:false, en:"Added 15 new Unique Items.", pl:"Dodano 15 nowych przedmiotów Unique (unikatowych)." },
  { d:0, b:false, en:"Added 3 new Divination Cards.", pl:"Dodano 3 nowe Divination Cards (karty wróżebne)." },
  { d:0, b:false, en:"Added the keywording and popup pinning system used in Path of Exile 2, allowing you to inspect certain words for more information. We will gradually be making more use of these systems in future patches.", pl:"Dodano system słów kluczowych (keywording) oraz przypinania wyskakujących okienek znany z Path of Exile 2, pozwalający sprawdzać wybrane słowa w poszukiwaniu dodatkowych informacji. Będziemy stopniowo szerzej wykorzystywać te systemy w przyszłych aktualizacjach." },
  { d:0, b:false, en:"Added the new Pearlescent Amulet base item type which has an all Elemental Resistances Implicit Modifier.", pl:"Dodano nowy bazowy typ przedmiotu Pearlescent Amulet, który posiada implicit (wrodzony modyfikator) na wszystkie odporności żywiołowe (all Elemental Resistances)." },
  { d:0, b:false, en:"When playing in a party, any player is now able to interact with the Expedition Detonator, Eldritch Altars, Harvest Plots, and Sentinels.", pl:"Podczas gry w drużynie każdy gracz może teraz wchodzić w interakcję z Expedition Detonator, Eldritch Altars, Harvest Plots oraz Sentinels." },
  { d:0, b:false, en:"Volatile Vaal Orbs and Crystallised Rancour now have dedicated slots in the Currency Stash Tab.", pl:"Volatile Vaal Orbs oraz Crystallised Rancour mają teraz dedykowane sloty w Currency Stash Tab (zakładce skrytki na waluty)." },
  { d:0, b:false, en:"Added 2 new crafting bench options, unlocked by default. Reroll 3 Modifiers on a Rare Item for a cost of 3 Chaos Orbs, and Reroll a Modifier on a Rare Item for a cost of 8 Chaos Orbs.", pl:"Dodano 2 nowe opcje crafting bench (stołu rzemieślniczego), odblokowane domyślnie. Przelosowanie 3 modyfikatorów na przedmiocie Rare za 3 Chaos Orbs oraz przelosowanie 1 modyfikatora na przedmiocie Rare za 8 Chaos Orbs." },
  { d:0, b:false, en:"Isla in Kingsmarch, Niko in the Mine Encampment and Einhar in the Menagerie are now all able to identify items for you.", pl:"Isla w Kingsmarch, Niko w Mine Encampment oraz Einhar w Menagerie potrafią teraz identyfikować dla ciebie przedmioty." },
  { d:0, b:false, en:"There is now a Crafting Bench available in every Town from Act 2 onwards.", pl:"W każdym mieście (Town) począwszy od Aktu 2 dostępny jest teraz Crafting Bench." },
  { d:0, b:false, en:"Catalysts now have a maximum stack size of 20 (previously 10).", pl:"Catalysts (katalizatory) mają teraz maksymalny rozmiar stosu 20 (poprzednio 10)." },
  { d:0, b:false, en:"The audio for most Raised Spectres should now be quieter.", pl:"Dźwięk większości Raised Spectres (przywołanych widm) powinien być teraz cichszy." },
  { d:0, b:false, en:"The waypoint in The Solaris Temple Level 1 in Act 8 has been moved closer to the Level 2 entrance.", pl:"Waypoint w The Solaris Temple Level 1 w Akcie 8 został przesunięty bliżej wejścia na Level 2." },
  { d:0, b:false, en:"Continued to incrementally improve the sound, art, effects and environments.", pl:"Kontynuowano stopniowe ulepszanie dźwięku, grafiki, efektów i środowisk." }
]});

PN({ id: "mercenaries-of-trarthus-as-a-core-league", title: { pl: "Mercenaries of Trarthus jako mechanika podstawowa", en: "Mercenaries of Trarthus as a Core League" }, lines: [
  { d:0, b:false, en:"Mercenaries from the lawless cities of Trarthus can now be found in areas from Act 3 onwards, awaiting you to accept their duel.", pl:"Mercenaries (najemników) z bezprawnych miast Trarthus można teraz spotkać na obszarach począwszy od Aktu 3, gdzie czekają, aż przyjmiesz ich pojedynek." },
  { d:0, b:false, en:"Wager for an item the Mercenary is carrying, if you lose, the gold you levied will be forfeited and the Mercenary teleports out. Win, however, and the Mercenary will aid you as an ally for a number of areas, in addition to winning the spoils of course.", pl:"Postaw zakład o przedmiot, który niesie Mercenary — jeśli przegrasz, wyłożone złoto przepada, a Mercenary teleportuje się poza obszar. Jeśli jednak wygrasz, Mercenary będzie ci pomagał jako sojusznik przez pewną liczbę obszarów, a do tego oczywiście zdobędziesz łupy." },
  { d:0, b:false, en:"You are guaranteed to find a Mercenary in the following Campaign Areas: The Sceptre of God, The Grand Arena, The Ridge, and The Hidden Underbelly. Mercenaries found in these areas will not have any Rucksack items.", pl:"Masz gwarancję spotkania Mercenary na następujących obszarach kampanii: The Sceptre of God, The Grand Arena, The Ridge oraz The Hidden Underbelly. Mercenaries napotkani na tych obszarach nie będą mieli żadnych przedmiotów Rucksack (z plecaka)." },
  { d:0, b:false, en:"Hired Mercenaries will scale up their passive stats and skills to the level of the current area you are in, up to a maximum of level 68. The level of items you can equip to your Mercenary is still capped by the level of the area where you found that Mercenary.", pl:"Wynajęci Mercenaries skalują swoje pasywne statystyki i umiejętności do poziomu obszaru, na którym aktualnie przebywasz, maksymalnie do poziomu 68. Poziom przedmiotów, które możesz założyć swojemu Mercenary, wciąż jest ograniczony poziomem obszaru, na którym go spotkałeś." },
  { d:0, b:false, en:"In Map areas, if you don't like anything the Mercenary offers, you're able to request their Warrant. A Warrant is a promise to return and duel again at a later date – a call to action which summons that specific Mercenary to a future Map, with the same set of Skills, but a new set of items. Warrants also allow you to trade specific Mercenaries to other players. A Mercenary will only grant their Warrant once however, preventing you from fighting that Mercenary in every single area.", pl:"Na obszarach Map, jeśli nie odpowiada ci nic, co oferuje Mercenary, możesz zażądać jego Warrant (nakazu). Warrant to obietnica powrotu i ponownego pojedynku w późniejszym czasie — wezwanie, które przywołuje tego konkretnego Mercenary na przyszłą Mapę, z tym samym zestawem umiejętności, lecz nowym zestawem przedmiotów. Warrants pozwalają też przekazywać (handlować) konkretnych Mercenaries innym graczom. Mercenary udzieli jednak swojego Warrant tylko raz, co uniemożliwia walkę z nim na każdym pojedynczym obszarze." },
  { d:0, b:false, en:"Unlike in the Mercenaries of Trarthus League, having a Mercenary does not count as a player party member, so having a Mercenary does not increase the Monster Life, or the Quantity or Rarity of Items dropped from Monsters.", pl:"W przeciwieństwie do ligi Mercenaries of Trarthus, posiadanie Mercenary nie liczy się jako członek drużyny, więc nie zwiększa Monster Life (życia potworów) ani ilości (Quantity) czy rzadkości (Rarity) przedmiotów wypadających z potworów." },
  { d:0, b:false, en:"Added the new Luminary Ascendancy Class for the Scion, which allows you to permanently Hire Mercenaries. Luminaries can have up to 3 permanently hired Mercenaries, 2 in reserve in Towns and Hideouts, and 1 as an active ally in combat. Unlike with regular Mercenaries, you can change the items permanently hired Mercenaries have equipped, opening up innumerate potential build possibilities.", pl:"Dodano nową klasę Ascendancy Luminary dla Scion, która pozwala na stałe wynajmować Mercenaries. Luminary może mieć do 3 na stałe wynajętych Mercenaries: 2 w rezerwie w miastach i hideoutach oraz 1 jako aktywnego sojusznika w walce. W przeciwieństwie do zwykłych Mercenaries, możesz zmieniać przedmioty założone na stałe wynajętym Mercenaries, co otwiera niezliczone możliwości buildów." },
  { d:0, b:false, en:"The following Unique items are now once again obtained through Mercenary encounters, and have been removed from the core drop pool: Azadi Crest, Binds of Bloody Vengeance, The Ghastly Theatre, Hand of Heresy, Howlcrack, and Scornflux.", pl:"Następujące przedmioty Unique są teraz ponownie zdobywane poprzez spotkania z Mercenaries i zostały usunięte z podstawowej puli dropu: Azadi Crest, Binds of Bloody Vengeance, The Ghastly Theatre, Hand of Heresy, Howlcrack oraz Scornflux." },
  { d:0, b:false, en:"Trarthan Gems are no longer possible rewards from Gem Chests in Heist. They again are obtained from Mercenary encounters.", pl:"Trarthan Gems nie są już możliwą nagrodą ze skrzyń Gem Chests w Heist. Ponownie zdobywa się je ze spotkań z Mercenaries." },
  { d:0, b:false, en:"Added support for Mercenaries of Trarthus to the Atlas Passive Tree.", pl:"Dodano wsparcie dla Mercenaries of Trarthus w Atlas Passive Tree (drzewku pasywnym Atlasu)." },
  { d:0, b:false, en:"Added a series of Trarthan Scarabs:", pl:"Dodano serię skarabeuszy Trarthan Scarabs:" },
  { d:1, b:false, en:"Trarthan Scarab: Area is inhabited by a Mercenary.", pl:"Trarthan Scarab: Obszar jest zamieszkany przez Mercenary." },
  { d:1, b:false, en:"Trarthan Scarab of Infamy: Mercenaries found in Area are Infamous, Mercenaries found in Area are accompanied by two Wild Mercenaries.", pl:"Trarthan Scarab of Infamy: Mercenaries na obszarze są Infamous (osławieni); Mercenaries na obszarze są w towarzystwie dwóch Wild Mercenaries (dzikich najemników)." },
  { d:1, b:false, en:"Trarthan Scarab of Renown: All Equipment Items on Mercenaries found in Area are Unique.", pl:"Trarthan Scarab of Renown: Wszystkie przedmioty ekwipunku na Mercenaries znalezionych na obszarze są Unique." },
  { d:1, b:false, en:"Trarthan Scarab of Surprising Alliances: Wild Rogue Exiles in Area have 50% chance to be accompanied by a Wild Mercenary, Wild Mercenaries have increased Difficulty for each Wild Mercenary in Area.", pl:"Trarthan Scarab of Surprising Alliances: Wild Rogue Exiles na obszarze mają 50% szansy na towarzystwo Wild Mercenary; Wild Mercenaries mają zwiększoną trudność (Difficulty) za każdego Wild Mercenary na obszarze." },
  { d:0, b:false, en:"Mercenary Rucksacks in Endgame Maps can no longer generate Orbs of Transmutation or Orbs of Augmentation.", pl:"Mercenary Rucksacks w Endgame Maps nie mogą już generować Orbs of Transmutation ani Orbs of Augmentation." },
  { d:0, b:false, en:"Added Searing Exarch Altar Modifiers that drop Mercenaries Scarabs.", pl:"Dodano modyfikatory Searing Exarch Altar, które upuszczają skarabeusze Mercenaries." },
  { d:0, b:false, en:"Hired Mercenaries now have an information sheet with a list of all their passive stats.", pl:"Wynajęci Mercenaries mają teraz kartę informacyjną z listą wszystkich swoich pasywnych statystyk." }
]});
/* @@SECTIONS@@ */
