/* =========================================================================
   PoE_PatchNotes — treść (hardcoded)
   Źródło: https://www.pathofexile.com/forum/view-thread/3985332/page/1
   Każda linia: { d: głębokość wcięcia, b: podnagłówek?, en: oryginał, pl: tłumaczenie }
   Nazwy własne PoE (przedmioty, gemy, mechaniki) pozostają po angielsku;
   tłumaczenie pomocnicze bywa podane w nawiasie.
   ========================================================================= */
window.PATCH_DATA = {
  meta: {
    version: "3.29.0",
    titleEn: "Content Update 3.29.0 — Path of Exile: Curse of the Allflame",
    titlePl: "Aktualizacja 3.29.0 — Path of Exile: Curse of the Allflame",
    source: "https://www.pathofexile.com/forum/view-thread/3985332/page/1",
    updated: "2026-07-17"
  },
  sections: []
};
function PN(s) { window.PATCH_DATA.sections.push(s); }
PN({ id: "the-curse-of-the-allflame-challenge-league", title: { pl: "Liga wyzwań: The Curse of the Allflame", en: "The Curse of the Allflame Challenge League" }, lines: [
  { d:0, b:false, en:"Meet Valerie, a dangerous corsair captain who needs your help retrieving long forgotten treasures from the icy depths of Wraeclast's oceans. Find Charts scattered across Wraeclast, board The Sovereign, and set sail!", pl:"Poznaj Valerie, niebezpieczną kapitan korsarzy, która potrzebuje twojej pomocy w wydobyciu dawno zapomnianych skarbów z lodowatych głębin oceanów Wraeclast. Odnajduj Charts (mapy morskie) rozsiane po całym Wraeclast, wejdź na pokład The Sovereign i wypłyń w morze!" },
  { d:0, b:false, en:"Dive to the ocean floor where lanterns imbued with the spark of the Allflame will shield you from the crushing waves. Explore and claim what you can while you can! Lost gold, valuable chests, and lurking threats await you...", pl:"Zanurkuj na dno oceanu, gdzie latarnie przepełnione iskrą Allflame osłonią cię przed miażdżącymi falami. Eksploruj i zgarniaj, co się da, póki możesz! Czekają na ciebie zagubione złoto, cenne skrzynie i czające się zagrożenia..." },
  { d:0, b:false, en:"Upon charting enough areas, connect them together to create a Voyage — one giant seafloor excursion. Revisit each chart to claim its rewards again, while also amplifying those rewards in several different ways.", pl:"Gdy naniesiesz na mapę wystarczająco wiele obszarów, połącz je w Voyage (rejs) — jedną wielką wyprawę po dnie morskim. Odwiedzaj ponownie każdą Chart, by znów zgarnąć jej nagrody, jednocześnie zwiększając je na kilka różnych sposobów." },
  { d:0, b:false, en:"Head belowdecks, and you'll find the heart of the ship at work. Feed it an item, and it will split into a multitude of ghostly outcomes, one of which you can keep for yourself.", pl:"Zejdź pod pokład, a zastaniesz przy pracy serce statku (heart of the ship). Nakarm je przedmiotem, a rozdzieli się on na mnóstwo widmowych wariantów, z których jeden możesz zatrzymać dla siebie." },
  { d:0, b:false, en:"Find valuable Ducats on the seafloor and use them to warp and twist items in ways not seen in centuries.", pl:"Znajduj cenne Ducats (dukaty) na dnie morza i używaj ich, by wypaczać i przekształcać przedmioty w sposób niewidziany od stuleci." },
  { d:0, b:false, en:"For more information about this expansion, check out pathofexile.com/allflame", pl:"Więcej informacji o tym dodatku znajdziesz na pathofexile.com/allflame" },
  { d:0, b:false, en:"With 3.29.0, there are Standard, Hardcore and Solo Self-Found variations of the Curse of the Allflame challenge league available. They have the same core mechanics and items. You can create private league versions of these leagues, with mods that make the game harder.", pl:"Wraz z 3.29.0 dostępne są warianty Standard, Hardcore oraz Solo Self-Found ligi wyzwań Curse of the Allflame. Mają one te same podstawowe mechaniki i przedmioty. Możesz tworzyć prywatne wersje tych lig, z modyfikatorami utrudniającymi grę." },
  { d:0, b:false, en:"The Hardcore variations of Curse of the Allflame are parented to their Standard Curse of the Allflame equivalent, meaning if you die in Hardcore Curse of the Allflame you can continue on in the Standard Curse of the Alfflame League.", pl:"Warianty Hardcore ligi Curse of the Allflame są podpięte pod swój odpowiednik Standard, co oznacza, że jeśli zginiesz w Hardcore Curse of the Allflame, możesz kontynuować grę w lidze Standard Curse of the Allflame." },
  { d:0, b:false, en:"The new Curse of the Allflame challenge league includes a set of 40 new challenges, and 8 new challenges in Ruthless Curse of the Allflame. There are microtransaction rewards for completing challenges that are only obtainable in this league. These rewards will be revealed in an upcoming news post.", pl:"Nowa liga wyzwań Curse of the Allflame zawiera zestaw 40 nowych wyzwań (challenges) oraz 8 nowych wyzwań w Ruthless Curse of the Allflame. Za ukończenie wyzwań przewidziano nagrody-mikrotransakcje dostępne wyłącznie w tej lidze. Nagrody te zostaną ujawnione w nadchodzącym wpisie z aktualnościami." },
  { d:0, b:false, en:"From the 19th challenge onwards and for every third challenge after that, you will receive pieces of the Curse of the Allflame Totem Pole decoration to display in your hideout. The Totem Pole permanently showcases how many of the Curse of the Allflame challenges you completed during the league.", pl:"Począwszy od 19. wyzwania oraz za każde trzecie wyzwanie po nim otrzymasz części dekoracji Curse of the Allflame Totem Pole (pala totemicznego) do umieszczenia w swoim hideout (kryjówce). Totem Pole na stałe prezentuje, ile wyzwań Curse of the Allflame ukończyłeś w trakcie ligi." }
]});

PN({ id: "new-content-and-features", title: { pl: "Nowa zawartość i funkcje", en: "New Content and Features" }, lines: [
  { d:0, b:false, en:"Introduced two new Bloodline Classes, one which is exclusive to the Curse of the Allflame challenge league.", pl:"Wprowadzono dwie nowe klasy Bloodline (rodowe), z których jedna jest dostępna wyłącznie w lidze wyzwań Curse of the Allflame." },
  { d:0, b:false, en:"Added a new Exceptional Skill Gem, Pact of Beidat: Cast a pact, Empowering spells that either fire projectiles, apply an effect to an area around a targeted location or fire chaining beams, causing them deal more damage and have enhanced coverage. However, using this skill also burdens you with an Affliction.", pl:"Dodano nowy Exceptional Skill Gem (wyjątkowy klejnot umiejętności), Pact of Beidat: Rzuca pakt, wzmacniając (Empower) zaklęcia, które wystrzeliwują pociski, nakładają efekt na obszar wokół wskazanego miejsca lub wystrzeliwują łańcuchujące wiązki — sprawiając, że zadają więcej obrażeń i mają zwiększony zasięg. Użycie tej umiejętności obarcza cię jednak Affliction (przypadłością)." },
  { d:0, b:false, en:"Added a new Exceptional Skill Gem, Pact of Ghorr: Cast a pact, Empowering your damage over time spells but burdening you with an Affliction. This skill also grants the Hunger of Ghorr buff for a duration causing Fleshrend to trigger periodically.", pl:"Dodano nowy Exceptional Skill Gem, Pact of Ghorr: Rzuca pakt, wzmacniając twoje zaklęcia zadające obrażenia w czasie (damage over time), lecz obarczając cię Affliction. Umiejętność ta nadaje też na pewien czas buff Hunger of Ghorr, sprawiając, że okresowo wyzwala się Fleshrend." },
  { d:0, b:false, en:"Added a new Exceptional Skill Gem, Pact of K'tash: Cast a pact, Empowering your damaging Vaal spells but burdening you with an Affliction. Empowered Vaal spells deal more damage, have less soul gain prevention duration and refund souls on use.", pl:"Dodano nowy Exceptional Skill Gem, Pact of K'tash: Rzuca pakt, wzmacniając twoje zadające obrażenia zaklęcia Vaal, lecz obarczając cię Affliction. Wzmocnione zaklęcia Vaal zadają więcej obrażeń, mają krótszy czas blokady pozyskiwania dusz (soul gain prevention) i zwracają dusze przy użyciu." },
  { d:0, b:false, en:"Added a new Exceptional Skill Gem, Pact of Lycia: Cast a pact, Empowering the next channelling spells you cast yourself but burdening you with an Affliction. Empowered spells deal more damage and periodically trigger lightning bolts while channelling.", pl:"Dodano nowy Exceptional Skill Gem, Pact of Lycia: Rzuca pakt, wzmacniając kolejne kanałowane (channelling) zaklęcia, które sam rzucisz, lecz obarczając cię Affliction. Wzmocnione zaklęcia zadają więcej obrażeń i okresowo wyzwalają błyskawice podczas kanałowania." },
  { d:0, b:false, en:"Added a new Exceptional Support Gem, Coursing Currents: Supports skills that hit enemies, providing increased effect of Chill and Shock inflicted with Supported Skills, causing enemies to be chilled when they are shocked by your hits, and shocked when they are chilled by your hits.", pl:"Dodano nowy Exceptional Support Gem (wyjątkowy klejnot wspierający), Coursing Currents: Wspiera umiejętności trafiające wrogów, zwiększając efekt Chill (schłodzenia) i Shock (porażenia) nakładanych wspieranymi umiejętnościami oraz sprawiając, że wrogowie zostają schłodzeni, gdy porazisz ich trafieniami, i porażeni, gdy schłodzisz ich trafieniami." },
  { d:0, b:false, en:"Added a new Exceptional Support Gem, Crystalfall: Supported Skills will Trigger Falling Crystal on Hit, causing a giant crystal of abyssal soulstone to be called from above, falling to slam down at the targeted location. Supports Slam skills. Cannot support triggered skills or skills used by things other than you.", pl:"Dodano nowy Exceptional Support Gem, Crystalfall: Wspierane umiejętności wyzwalają Falling Crystal (spadający kryształ) przy trafieniu, przywołując z góry gigantyczny kryształ abyssal soulstone, który spada, uderzając we wskazane miejsce. Wspiera umiejętności typu Slam. Nie może wspierać umiejętności wyzwalanych ani używanych przez cokolwiek innego niż ty." },
  { d:0, b:false, en:"Added a new Intelligence/Strength Skill, Mana-Infused Staff: Infuses your staff with arcane energy, lowering your mana costs and increasing your chance to block. When you block, you release an arcane wave, damaging enemies in a ring-shaped area over a duration.", pl:"Dodano nową umiejętność Intelligence/Strength, Mana-Infused Staff: Przesyca twój staff (kostur) energią arkany, obniżając koszty many i zwiększając szansę na blok. Gdy blokujesz, uwalniasz falę arkany, zadającą wrogom obrażenia w obszarze w kształcie pierścienia przez pewien czas." },
  { d:0, b:false, en:"Added a new Strength/Intelligence Transfigured Skill, Divine Blast of Radiance: Project a beam of holy light from your shield to a targeted location, causing an implosion of holy energy. This energy then lingers for a short duration as an orb, periodically releasing larger explosions. Increases and reductions to attack speed affect the rate at which explosions occur.", pl:"Dodano nową umiejętność Transfigured (przekształconą) Strength/Intelligence, Divine Blast of Radiance: Wystrzeliwuje wiązkę świętego światła z twojej tarczy we wskazane miejsce, wywołując implozję świętej energii. Energia ta utrzymuje się następnie przez krótki czas jako kula, okresowo uwalniając większe eksplozje. Zwiększenia i zmniejszenia attack speed (szybkości ataku) wpływają na tempo występowania eksplozji." },
  { d:0, b:false, en:"Added a new Strength/Intelligence Transfigured Skill, Holy Hammers of Spirals: Slam the ground, consuming all Power Charges and calling down a cascade of holy hammers from above in an outward spiral. Further hammers are called down for each Power Charge consumed. Requires a Mace, Sceptre or Staff.", pl:"Dodano nową umiejętność Transfigured Strength/Intelligence, Holy Hammers of Spirals: Uderza w ziemię, zużywając wszystkie Power Charges (ładunki mocy) i sprowadzając z góry kaskadę świętych młotów w rozchodzącej się spirali. Za każdy zużyty Power Charge sprowadzanych jest więcej młotów. Wymaga broni Mace, Sceptre lub Staff." },
  { d:0, b:false, en:"Added a new Strength/Intelligence Transfigured Skill, Holy Sweep of Hammerfalls: Swings a two handed mace or a staff in a circle, calling down waves of holy hammers for a duration. Increases and reductions to Attack Speed will affect the rate at which these hammerfalls occur.", pl:"Dodano nową umiejętność Transfigured Strength/Intelligence, Holy Sweep of Hammerfalls: Wykonuje zamach dwuręcznym maczugą (two handed mace) lub kosturem (staff) w okręgu, sprowadzając fale świętych młotów przez pewien czas. Zwiększenia i zmniejszenia Attack Speed wpływają na tempo, w jakim występują te uderzenia młotów." },
  { d:0, b:false, en:"Added a new Strength/Intelligence Transfigured Skill, Reap of Butchery: A bloody scythe swipes around you, applying a physical damage over time debuff and hitting enemies with physical damage. If any survive, you gain a blood charge which raises the damage and cost of the skill. Players can have 5 maximum blood charges.", pl:"Dodano nową umiejętność Transfigured Strength/Intelligence, Reap of Butchery: Krwawa kosa tnie wokół ciebie, nakładając debuff fizycznych obrażeń w czasie (physical damage over time) i trafiając wrogów obrażeniami fizycznymi. Jeśli ktokolwiek przeżyje, zyskujesz blood charge (ładunek krwi), który zwiększa obrażenia i koszt umiejętności. Gracze mogą mieć maksymalnie 5 blood charges." },
  { d:0, b:false, en:"Added 15 new Unique Items.", pl:"Dodano 15 nowych przedmiotów Unique (unikatowych)." },
  { d:0, b:false, en:"Added 3 new Divination Cards.", pl:"Dodano 3 nowe Divination Cards (karty wróżebne)." },
  { d:0, b:false, en:"Added the keywording and popup pinning system used in Path of Exile 2, allowing you to inspect certain words for more information. We will gradually be making more use of these systems in future patches.", pl:"Dodano system słów kluczowych (keywording) oraz przypinania wyskakujących okienek znany z Path of Exile 2, pozwalający sprawdzać wybrane słowa w poszukiwaniu dodatkowych informacji. Będziemy stopniowo szerzej wykorzystywać te systemy w przyszłych aktualizacjach." },
  { d:0, b:false, en:"Added the new Pearlescent Amulet base item type which has an all Elemental Resistances Implicit Modifier.", pl:"Dodano nowy bazowy typ przedmiotu Pearlescent Amulet, który posiada implicit (wrodzony modyfikator) na wszystkie odporności żywiołowe (all Elemental Resistances)." },
  { d:0, b:false, en:"When playing in a party, any player is now able to interact with the Expedition Detonator, Eldritch Altars, Harvest Plots, and Sentinels.", pl:"Podczas gry w drużynie każdy gracz może teraz wchodzić w interakcję z Expedition Detonator, Eldritch Altars, Harvest Plots oraz Sentinels." },
  { d:0, b:false, en:"Volatile Vaal Orbs and Crystallised Rancour now have dedicated slots in the Currency Stash Tab.", pl:"Volatile Vaal Orbs oraz Crystallised Rancour mają teraz dedykowane sloty w Currency Stash Tab (zakładce skrytki na waluty)." },
  { d:0, b:false, en:"Added 2 new crafting bench options, unlocked by default. Reroll 3 Modifiers on a Rare Item for a cost of 3 Chaos Orbs, and Reroll a Modifier on a Rare Item for a cost of 8 Chaos Orbs.", pl:"Dodano 2 nowe opcje crafting bench (stołu rzemieślniczego), odblokowane domyślnie. Przelosowanie 3 modyfikatorów na przedmiocie Rare za 3 Chaos Orbs oraz przelosowanie 1 modyfikatora na przedmiocie Rare za 8 Chaos Orbs." },
  { d:0, b:false, en:"Isla in Kingsmarch, Niko in the Mine Encampment and Einhar in the Menagerie are now all able to identify items for you.", pl:"Isla w Kingsmarch, Niko w Mine Encampment oraz Einhar w Menagerie potrafią teraz identyfikować dla ciebie przedmioty." },
  { d:0, b:false, en:"There is now a Crafting Bench available in every Town from Act 2 onwards.", pl:"W każdym mieście (Town) począwszy od Aktu 2 dostępny jest teraz Crafting Bench." },
  { d:0, b:false, en:"Catalysts now have a maximum stack size of 20 (previously 10).", pl:"Catalysts (katalizatory) mają teraz maksymalny rozmiar stosu 20 (poprzednio 10)." },
  { d:0, b:false, en:"The audio for most Raised Spectres should now be quieter.", pl:"Dźwięk większości Raised Spectres (przywołanych widm) powinien być teraz cichszy." },
  { d:0, b:false, en:"The waypoint in The Solaris Temple Level 1 in Act 8 has been moved closer to the Level 2 entrance.", pl:"Waypoint w The Solaris Temple Level 1 w Akcie 8 został przesunięty bliżej wejścia na Level 2." },
  { d:0, b:false, en:"Continued to incrementally improve the sound, art, effects and environments.", pl:"Kontynuowano stopniowe ulepszanie dźwięku, grafiki, efektów i środowisk." }
]});

PN({ id: "mercenaries-of-trarthus-as-a-core-league", title: { pl: "Mercenaries of Trarthus jako mechanika podstawowa", en: "Mercenaries of Trarthus as a Core League" }, lines: [
  { d:0, b:false, en:"Mercenaries from the lawless cities of Trarthus can now be found in areas from Act 3 onwards, awaiting you to accept their duel.", pl:"Mercenaries (najemników) z bezprawnych miast Trarthus można teraz spotkać na obszarach począwszy od Aktu 3, gdzie czekają, aż przyjmiesz ich pojedynek." },
  { d:0, b:false, en:"Wager for an item the Mercenary is carrying, if you lose, the gold you levied will be forfeited and the Mercenary teleports out. Win, however, and the Mercenary will aid you as an ally for a number of areas, in addition to winning the spoils of course.", pl:"Postaw zakład o przedmiot, który niesie Mercenary — jeśli przegrasz, wyłożone złoto przepada, a Mercenary teleportuje się poza obszar. Jeśli jednak wygrasz, Mercenary będzie ci pomagał jako sojusznik przez pewną liczbę obszarów, a do tego oczywiście zdobędziesz łupy." },
  { d:0, b:false, en:"You are guaranteed to find a Mercenary in the following Campaign Areas: The Sceptre of God, The Grand Arena, The Ridge, and The Hidden Underbelly. Mercenaries found in these areas will not have any Rucksack items.", pl:"Masz gwarancję spotkania Mercenary na następujących obszarach kampanii: The Sceptre of God, The Grand Arena, The Ridge oraz The Hidden Underbelly. Mercenaries napotkani na tych obszarach nie będą mieli żadnych przedmiotów Rucksack (z plecaka)." },
  { d:0, b:false, en:"Hired Mercenaries will scale up their passive stats and skills to the level of the current area you are in, up to a maximum of level 68. The level of items you can equip to your Mercenary is still capped by the level of the area where you found that Mercenary.", pl:"Wynajęci Mercenaries skalują swoje pasywne statystyki i umiejętności do poziomu obszaru, na którym aktualnie przebywasz, maksymalnie do poziomu 68. Poziom przedmiotów, które możesz założyć swojemu Mercenary, wciąż jest ograniczony poziomem obszaru, na którym go spotkałeś." },
  { d:0, b:false, en:"In Map areas, if you don't like anything the Mercenary offers, you're able to request their Warrant. A Warrant is a promise to return and duel again at a later date – a call to action which summons that specific Mercenary to a future Map, with the same set of Skills, but a new set of items. Warrants also allow you to trade specific Mercenaries to other players. A Mercenary will only grant their Warrant once however, preventing you from fighting that Mercenary in every single area.", pl:"Na obszarach Map, jeśli nie odpowiada ci nic, co oferuje Mercenary, możesz zażądać jego Warrant (nakazu). Warrant to obietnica powrotu i ponownego pojedynku w późniejszym czasie — wezwanie, które przywołuje tego konkretnego Mercenary na przyszłą Mapę, z tym samym zestawem umiejętności, lecz nowym zestawem przedmiotów. Warrants pozwalają też przekazywać (handlować) konkretnych Mercenaries innym graczom. Mercenary udzieli jednak swojego Warrant tylko raz, co uniemożliwia walkę z nim na każdym pojedynczym obszarze." },
  { d:0, b:false, en:"Unlike in the Mercenaries of Trarthus League, having a Mercenary does not count as a player party member, so having a Mercenary does not increase the Monster Life, or the Quantity or Rarity of Items dropped from Monsters.", pl:"W przeciwieństwie do ligi Mercenaries of Trarthus, posiadanie Mercenary nie liczy się jako członek drużyny, więc nie zwiększa Monster Life (życia potworów) ani ilości (Quantity) czy rzadkości (Rarity) przedmiotów wypadających z potworów." },
  { d:0, b:false, en:"Added the new Luminary Ascendancy Class for the Scion, which allows you to permanently Hire Mercenaries. Luminaries can have up to 3 permanently hired Mercenaries, 2 in reserve in Towns and Hideouts, and 1 as an active ally in combat. Unlike with regular Mercenaries, you can change the items permanently hired Mercenaries have equipped, opening up innumerate potential build possibilities.", pl:"Dodano nową klasę Ascendancy Luminary dla Scion, która pozwala na stałe wynajmować Mercenaries. Luminary może mieć do 3 na stałe wynajętych Mercenaries: 2 w rezerwie w miastach i hideoutach oraz 1 jako aktywnego sojusznika w walce. W przeciwieństwie do zwykłych Mercenaries, możesz zmieniać przedmioty założone na stałe wynajętym Mercenaries, co otwiera niezliczone możliwości buildów." },
  { d:0, b:false, en:"The following Unique items are now once again obtained through Mercenary encounters, and have been removed from the core drop pool: Azadi Crest, Binds of Bloody Vengeance, The Ghastly Theatre, Hand of Heresy, Howlcrack, and Scornflux.", pl:"Następujące przedmioty Unique są teraz ponownie zdobywane poprzez spotkania z Mercenaries i zostały usunięte z podstawowej puli dropu: Azadi Crest, Binds of Bloody Vengeance, The Ghastly Theatre, Hand of Heresy, Howlcrack oraz Scornflux." },
  { d:0, b:false, en:"Trarthan Gems are no longer possible rewards from Gem Chests in Heist. They again are obtained from Mercenary encounters.", pl:"Trarthan Gems nie są już możliwą nagrodą ze skrzyń Gem Chests w Heist. Ponownie zdobywa się je ze spotkań z Mercenaries." },
  { d:0, b:false, en:"Added support for Mercenaries of Trarthus to the Atlas Passive Tree.", pl:"Dodano wsparcie dla Mercenaries of Trarthus w Atlas Passive Tree (drzewku pasywnym Atlasu)." },
  { d:0, b:false, en:"Added a series of Trarthan Scarabs:", pl:"Dodano serię skarabeuszy Trarthan Scarabs:" },
  { d:1, b:false, en:"Trarthan Scarab: Area is inhabited by a Mercenary.", pl:"Trarthan Scarab: Obszar jest zamieszkany przez Mercenary." },
  { d:1, b:false, en:"Trarthan Scarab of Infamy: Mercenaries found in Area are Infamous, Mercenaries found in Area are accompanied by two Wild Mercenaries.", pl:"Trarthan Scarab of Infamy: Mercenaries na obszarze są Infamous (osławieni); Mercenaries na obszarze są w towarzystwie dwóch Wild Mercenaries (dzikich najemników)." },
  { d:1, b:false, en:"Trarthan Scarab of Renown: All Equipment Items on Mercenaries found in Area are Unique.", pl:"Trarthan Scarab of Renown: Wszystkie przedmioty ekwipunku na Mercenaries znalezionych na obszarze są Unique." },
  { d:1, b:false, en:"Trarthan Scarab of Surprising Alliances: Wild Rogue Exiles in Area have 50% chance to be accompanied by a Wild Mercenary, Wild Mercenaries have increased Difficulty for each Wild Mercenary in Area.", pl:"Trarthan Scarab of Surprising Alliances: Wild Rogue Exiles na obszarze mają 50% szansy na towarzystwo Wild Mercenary; Wild Mercenaries mają zwiększoną trudność (Difficulty) za każdego Wild Mercenary na obszarze." },
  { d:0, b:false, en:"Mercenary Rucksacks in Endgame Maps can no longer generate Orbs of Transmutation or Orbs of Augmentation.", pl:"Mercenary Rucksacks w Endgame Maps nie mogą już generować Orbs of Transmutation ani Orbs of Augmentation." },
  { d:0, b:false, en:"Added Searing Exarch Altar Modifiers that drop Mercenaries Scarabs.", pl:"Dodano modyfikatory Searing Exarch Altar, które upuszczają skarabeusze Mercenaries." },
  { d:0, b:false, en:"Hired Mercenaries now have an information sheet with a list of all their passive stats.", pl:"Wynajęci Mercenaries mają teraz kartę informacyjną z listą wszystkich swoich pasywnych statystyk." }
]});
PN({ id: "abyss-revamp", title: { pl: "Przebudowa Abyss", en: "Abyss Revamp" }, lines: [
  { d:0, b:false, en:"Abyss has received function changes to the mechanic to improve the gameplay significantly.", pl:"Mechanika Abyss otrzymała zmiany funkcjonalne, które znacząco poprawiają rozgrywkę." },
  { d:0, b:false, en:"Abyssal Pits, and the cracks leading up to them, are now already opened before you approach, subjugating the souls of the enemies unlucky enough to be within its influence.", pl:"Abyssal Pits (otchłanne doły) oraz prowadzące do nich cracks (pęknięcia) są teraz otwarte, zanim się do nich zbliżysz, podporządkowując sobie dusze wrogów, którzy mieli pecha znaleźć się w ich zasięgu." },
  { d:0, b:false, en:"Slaying these enemies sends their souls into the pit, drawing the attention and ire of the minions of Kulemak dwelling beneath. Upon slaying enough of them, the Abyssal legion will spill forth from their domain.", pl:"Zabijanie tych wrogów wysyła ich dusze do dołu, ściągając uwagę i gniew sług Kulemaka przebywających w głębinie. Gdy zabijesz ich wystarczająco wielu, Abyssal legion (otchłanny legion) wyleje się ze swojej domeny." },
  { d:0, b:false, en:"Gone are the days of chasing a meandering Abyssal crack around a Map, often backwards.", pl:"Minęły czasy gonienia wijącego się Abyssal crack po całej Mapie, często w kierunku powrotnym." },
  { d:0, b:false, en:"Alongside this revamp, a new Abyss Endgame Pinnacle Boss has been added, with its own set of brand new Unique items.", pl:"Wraz z tą przebudową dodano nowego Abyss Endgame Pinnacle Boss (szczytowego bossa endgame), z własnym zestawem zupełnie nowych przedmiotów Unique." },
  { d:0, b:false, en:"Abyss is now the exclusive source of Abyssal Jewels and Stygian Vises, though Abyssal Jewels can still be obtained rarely within Abyss Biomes in Delve.", pl:"Abyss jest teraz wyłącznym źródłem Abyssal Jewels oraz Stygian Vises, choć Abyssal Jewels wciąż można rzadko zdobyć w Abyss Biomes w Delve." },
  { d:0, b:false, en:"Abyssal Delirium Orbs can no longer be obtained.", pl:"Abyssal Delirium Orbs nie są już możliwe do zdobycia." },
  { d:0, b:false, en:"Abyssal Jewels can no longer roll increased Damage with Hits and Ailments against Abyssal Monsters, Minions deal increased Damage with Hits and Ailments against Abyssal Monsters, additional Physical Damage Reduction against Abyssal Monsters, or additional Physical Damage Reduction if you weren't Damaged by a Hit Recently.", pl:"Abyssal Jewels nie mogą już losować modyfikatorów: increased Damage with Hits and Ailments against Abyssal Monsters, Minions deal increased Damage with Hits and Ailments against Abyssal Monsters, additional Physical Damage Reduction against Abyssal Monsters, ani additional Physical Damage Reduction if you weren't Damaged by a Hit Recently." },
  { d:0, b:false, en:"The base Abyss Scarab now has a limit of 5 from 2. If an area already has an Abyss, modifiers that cause areas to contain additional Abysses will instead add two additional pits.", pl:"Podstawowy Abyss Scarab ma teraz limit 5 zamiast 2. Jeśli obszar już zawiera Abyss, modyfikatory dodające obszarom kolejne Abysses dodadzą zamiast tego dwa dodatkowe pits (doły)." },
  { d:0, b:false, en:"The Abyss Scarab of Multitudes now grants Abyss Chasms in Area spawn 100% increased Monsters per Soul fed.", pl:"Abyss Scarab of Multitudes nadaje teraz: Abyss Chasms na obszarze przywołują 100% zwiększoną liczbę Monsters za każdą nakarmioną Soul (duszę)." },
  { d:0, b:false, en:"The Abyss Scarab of Edifice has been renamed to Abyss Scarab of Crystals and causes Abyss Pits in Area that do not contain a reward instead create an Abyssal Crystal.", pl:"Abyss Scarab of Edifice zmienił nazwę na Abyss Scarab of Crystals i sprawia, że Abyss Pits na obszarze, które nie zawierają nagrody, tworzą zamiast tego Abyssal Crystal." },
  { d:0, b:false, en:"The Abyss Scarab of Profound Depth has been renamed to Abyssal Scarab of the Consort and causes one Abyss Pit in Area to spawn an Abyssal Consort.", pl:"Abyss Scarab of Profound Depth zmienił nazwę na Abyssal Scarab of the Consort i sprawia, że jeden Abyss Pit na obszarze przywołuje Abyssal Consort." },
  { d:0, b:false, en:"The following changes have been made to the highest tier Modifiers for Abyssal Jewels, their lower tier counterparts have been adjusted accordingly:", pl:"Wprowadzono następujące zmiany w modyfikatorach najwyższego tieru dla Abyssal Jewels; ich odpowiedniki z niższych tierów dostosowano proporcjonalnie:" },
  { d:1, b:false, en:"20% increased Effect of Cold Ailments (previously up to 15%).", pl:"20% zwiększonego Effect of Cold Ailments (poprzednio do 15%)." },
  { d:1, b:false, en:"20% increased Effect of Lightning Ailments (previously up to 15%).", pl:"20% zwiększonego Effect of Lightning Ailments (poprzednio do 15%)." },
  { d:1, b:false, en:"8% increased Impale Effect (previously up to 6%). Impale Effect no longer rolls on Hypnotic or Ghastly Eye Jewels.", pl:"8% zwiększonego Impale Effect (poprzednio do 6%). Impale Effect nie losuje się już na Hypnotic ani Ghastly Eye Jewels." },
  { d:1, b:false, en:"+34 to maximum Mana (previously up to +40).", pl:"+34 do maksymalnej Many (poprzednio do +40)." },
  { d:1, b:false, en:"5% of Damage taken Recouped as Mana (previously up to 3%).", pl:"5% otrzymanych obrażeń Recouped jako Mana (poprzednio do 3%)." },
  { d:1, b:false, en:"Adds 30 to 42 Fire Damage to Spells (previously up to 23 to 32).", pl:"Dodaje 30–42 Fire Damage to Spells (poprzednio do 23–32)." },
  { d:1, b:false, en:"Adds 28 to 38 Cold Damage to Spells (previously up to 23 to 32).", pl:"Dodaje 28–38 Cold Damage to Spells (poprzednio do 23–32)." },
  { d:1, b:false, en:"Adds 8 to 59 Lightning Damage to Spells (previously up to 6 to 45).", pl:"Dodaje 8–59 Lightning Damage to Spells (poprzednio do 6–45)." },
  { d:1, b:false, en:"Adds 23 to 32 Physical Damage to Spells (previously up to 16 to 22).", pl:"Dodaje 23–32 Physical Damage to Spells (poprzednio do 16–22)." },
  { d:1, b:false, en:"Adds 23 to 32 Chaos Damage to Spells (previously up to 16 to 22).", pl:"Dodaje 23–32 Chaos Damage to Spells (poprzednio do 16–22)." },
  { d:1, b:false, en:"Adds 33 to 44 Fire Damage to Spells while holding a Shield/wielding a Two Handed Weapon/Dual Wielding (previously up to 25 to 34).", pl:"Dodaje 33–44 Fire Damage to Spells, gdy trzymasz Shield / władasz Two Handed Weapon / Dual Wielding (poprzednio do 25–34)." },
  { d:1, b:false, en:"Adds 20 to 41 Cold Damage to Spells while holding a Shield/wielding a Two Handed Weapon/Dual Wielding (previously up to 25 to 34).", pl:"Dodaje 20–41 Cold Damage to Spells, gdy trzymasz Shield / władasz Two Handed Weapon / Dual Wielding (poprzednio do 25–34)." },
  { d:1, b:false, en:"Adds 8 to 66 Lightning Damage to Spells while holding a Shield/wielding a Two Handed Weapon/Dual Wielding (previously up to 6 to 51).", pl:"Dodaje 8–66 Lightning Damage to Spells, gdy trzymasz Shield / władasz Two Handed Weapon / Dual Wielding (poprzednio do 6–51)." },
  { d:1, b:false, en:"Adds 24 to 35 Physical Damage to Spells while holding a Shield/wielding a Two Handed Weapon/Dual Wielding (previously up to 17 to 24).", pl:"Dodaje 24–35 Physical Damage to Spells, gdy trzymasz Shield / władasz Two Handed Weapon / Dual Wielding (poprzednio do 17–24)." },
  { d:1, b:false, en:"Adds 24 to 35 Chaos Damage to Spells while holding a Shield/wielding a Two Handed Weapon/Dual Wielding (previously up to 17 to 24).", pl:"Dodaje 24–35 Chaos Damage to Spells, gdy trzymasz Shield / władasz Two Handed Weapon / Dual Wielding (poprzednio do 17–24)." },
  { d:1, b:false, en:"8% chance to Gain Unholy Might for 4 seconds on Melee Kill (previously up to 5%).", pl:"8% szansy na Gain Unholy Might przez 4 sekundy przy Melee Kill (poprzednio do 5%)." },
  { d:1, b:false, en:"Minions have 15% increased Movement Speed (previously up to 10%).", pl:"Minions mają 15% zwiększonego Movement Speed (poprzednio do 10%)." },
  { d:1, b:false, en:"25% reduced Effect of Curses on you while on Consecrated Ground (previously up to 15%).", pl:"25% zmniejszonego Effect of Curses on you, gdy stoisz na Consecrated Ground (poprzednio do 15%)." },
  { d:1, b:false, en:"20% chance to Avoid Elemental Ailments while you have Elusive (previously up to 10%).", pl:"20% szansy na Avoid Elemental Ailments, gdy masz Elusive (poprzednio do 10%)." },
  { d:1, b:false, en:"Enemies Hindered by you have 35% reduced Life Regeneration rate (previously up to 20%).", pl:"Wrogowie Hindered przez ciebie mają 35% zmniejszonego Life Regeneration rate (poprzednio do 20%)." },
  { d:1, b:false, en:"Enemies Blinded by you have 30% reduced Critical Strike Chance (previously up to 20%).", pl:"Wrogowie Blinded przez ciebie mają 30% zmniejszonej Critical Strike Chance (poprzednio do 20%)." }
]});

PN({ id: "legion-revamp", title: { pl: "Przebudowa Legion", en: "Legion Revamp" }, lines: [
  { d:0, b:false, en:"Added four Crystals of Permutation to the Domain of Timeless Conflict, which you can place Enshrouded Items into.", pl:"Dodano cztery Crystals of Permutation do Domain of Timeless Conflict, do których możesz umieszczać Enshrouded Items." },
  { d:0, b:false, en:"Enshrouded items can be transformed to another Unique of the same item class, with a Vestigial implicit modifier derived from the Enshrouded item.", pl:"Enshrouded items można przekształcić w inny Unique tej samej klasy przedmiotu, z Vestigial implicit modifier (szczątkowym modyfikatorem wrodzonym) wywiedzionym z danego Enshrouded item." },
  { d:0, b:false, en:"Killing monsters in the Domain will charge the Enshrouded Item. When the Enshrouded item is fully charged you can interact with the Crystal of Permutation to drop the new item.", pl:"Zabijanie potworów w Domain ładuje Enshrouded Item. Gdy Enshrouded item jest w pełni naładowany, możesz wejść w interakcję z Crystal of Permutation, aby wypuścić nowy przedmiot." },
  { d:0, b:false, en:"Added the following new Currency items that can drop from Legion Generals in Map areas which can Enshroud Unique items: Karui Enshrouding Crystal, Imperial Enshrouding Crystal, Maraketh Enshrouding Crystal, Templar Enshrouding Crystal, and Vaal Enshrouding Crystal. These items cannot drop in the Domain of Timeless Conflict.", pl:"Dodano następujące nowe przedmioty Currency, które mogą wypaść z Legion Generals na obszarach Map i które potrafią Enshroud (spowić) przedmioty Unique: Karui Enshrouding Crystal, Imperial Enshrouding Crystal, Maraketh Enshrouding Crystal, Templar Enshrouding Crystal oraz Vaal Enshrouding Crystal. Przedmioty te nie mogą wypaść w Domain of Timeless Conflict." },
  { d:0, b:false, en:"Legion encounters will now automatically break out all Monsters in the encounter if you have broken out 90% of the total Monsters, as well as Chests, Sergeants, and Generals.", pl:"Spotkania Legion automatycznie uwolnią teraz wszystkie Monsters w spotkaniu, jeśli uwolnisz 90% wszystkich Monsters, a także Chests, Sergeants i Generals." },
  { d:0, b:false, en:"Unrelenting Timeless Emblems have been removed, existing items have been converted to regular Timeless Emblems.", pl:"Unrelenting Timeless Emblems zostały usunięte; istniejące przedmioty przekonwertowano na zwykłe Timeless Emblems." },
  { d:0, b:false, en:"The modifiers applied by Timeless Emblems have been adjusted, the new modifiers applied by each Emblem are as follows:", pl:"Modyfikatory nadawane przez Timeless Emblems zostały dostosowane; nowe modyfikatory nadawane przez każdy Emblem są następujące:" },
  { d:1, b:true, en:"Timeless Eternal Emblem:", pl:"Timeless Eternal Emblem:" },
  { d:2, b:false, en:"10% increased Experience Gain.", pl:"10% zwiększonego Experience Gain (zysku doświadczenia)." },
  { d:2, b:false, en:"20% increased Reward progress from Monster Kills.", pl:"20% zwiększonego postępu Reward z Monster Kills." },
  { d:2, b:false, en:"Monsters deal 10% increased Damage.", pl:"Monsters zadają 10% zwiększonych Damage." },
  { d:2, b:false, en:"Monsters have 10% increased Toughness for each time they have been Revived.", pl:"Monsters mają 10% zwiększonego Toughness za każde ich Revive (wskrzeszenie)." },
  { d:2, b:false, en:"Monsters have 10% increased Accuracy Rating for each time they have been Revived.", pl:"Monsters mają 10% zwiększonego Accuracy Rating za każde ich Revive." },
  { d:2, b:false, en:"Monsters have 5% increased Area of Effect for each time they have been Revived.", pl:"Monsters mają 5% zwiększonego Area of Effect za każde ich Revive." },
  { d:1, b:true, en:"Timeless Karui Emblem:", pl:"Timeless Karui Emblem:" },
  { d:2, b:false, en:"10% increased Experience Gain.", pl:"10% zwiększonego Experience Gain (zysku doświadczenia)." },
  { d:2, b:false, en:"20% increased Reward progress from Monster Kills.", pl:"20% zwiększonego postępu Reward z Monster Kills." },
  { d:2, b:false, en:"Monsters deal 10% increased Damage.", pl:"Monsters zadają 10% zwiększonych Damage." },
  { d:2, b:false, en:"Monsters have 10% increased Toughness for each time they have been Revived.", pl:"Monsters mają 10% zwiększonego Toughness za każde ich Revive (wskrzeszenie)." },
  { d:2, b:false, en:"Monsters gain 50% increased Critical Strike Chance each time they are Revived.", pl:"Monsters zyskują 50% zwiększonej Critical Strike Chance za każde Revive." },
  { d:2, b:false, en:"Monsters gain +5% to Critical Strike Multiplier each time they are Revived", pl:"Monsters zyskują +5% do Critical Strike Multiplier za każde Revive." },
  { d:1, b:true, en:"Timeless Maraketh Emblem:", pl:"Timeless Maraketh Emblem:" },
  { d:2, b:false, en:"10% increased Experience Gain.", pl:"10% zwiększonego Experience Gain (zysku doświadczenia)." },
  { d:2, b:false, en:"20% increased Reward progress from Monster Kills.", pl:"20% zwiększonego postępu Reward z Monster Kills." },
  { d:2, b:false, en:"Monsters deal 10% increased Damage.", pl:"Monsters zadają 10% zwiększonych Damage." },
  { d:2, b:false, en:"Monsters have 10% increased Toughness for each time they have been Revived.", pl:"Monsters mają 10% zwiększonego Toughness za każde ich Revive (wskrzeszenie)." },
  { d:2, b:false, en:"Monsters have 5% increased Attack and Cast Speed for each time they have been Revived.", pl:"Monsters mają 5% zwiększonej Attack and Cast Speed za każde ich Revive." },
  { d:1, b:true, en:"Timeless Templar Emblem:", pl:"Timeless Templar Emblem:" },
  { d:2, b:false, en:"10% increased Experience Gain.", pl:"10% zwiększonego Experience Gain (zysku doświadczenia)." },
  { d:2, b:false, en:"20% increased Reward progress from Monster Kills.", pl:"20% zwiększonego postępu Reward z Monster Kills." },
  { d:2, b:false, en:"Monsters deal 10% increased Damage.", pl:"Monsters zadają 10% zwiększonych Damage." },
  { d:2, b:false, en:"Monsters have 10% increased Toughness for each time they have been Revived.", pl:"Monsters mają 10% zwiększonego Toughness za każde ich Revive (wskrzeszenie)." },
  { d:2, b:false, en:"Monsters Penetrate 3% of Enemy Elemental Resistances for each time they have been Revived.", pl:"Monsters Penetrują 3% Elemental Resistances wroga za każde ich Revive." },
  { d:1, b:true, en:"Timeless Vaal Emblem:", pl:"Timeless Vaal Emblem:" },
  { d:2, b:false, en:"10% increased Experience Gain.", pl:"10% zwiększonego Experience Gain (zysku doświadczenia)." },
  { d:2, b:false, en:"20% increased Reward progress from Monster Kills.", pl:"20% zwiększonego postępu Reward z Monster Kills." },
  { d:2, b:false, en:"Monsters deal 10% increased Damage.", pl:"Monsters zadają 10% zwiększonych Damage." },
  { d:2, b:false, en:"Monsters have 10% increased Toughness for each time they have been Revived.", pl:"Monsters mają 10% zwiększonego Toughness za każde ich Revive (wskrzeszenie)." },
  { d:2, b:false, en:"Monsters gain 5% of Physical Damage as Extra Chaos Damage for each time they have been Revived.", pl:"Monsters zyskują 5% Physical Damage jako Extra Chaos Damage za każde ich Revive." },
  { d:0, b:false, en:"Incubators no longer be obtained. Existing Incubators and Incubated items in Standard Leagues are unaffected by this change.", pl:"Incubators nie są już możliwe do zdobycia. Istniejące Incubators oraz przedmioty z Incubated w ligach Standard nie są objęte tą zmianą." },
  { d:0, b:false, en:"The Timeless Delirium Orb is no longer obtainable, but existing items in Standard can still be used.", pl:"Timeless Delirium Orb nie jest już możliwy do zdobycia, ale istniejące przedmioty w Standard nadal można wykorzystać." },
  { d:0, b:false, en:"Rog no longer has a craft to apply a random Incubator to an item.", pl:"Rog nie oferuje już craftu nakładającego losowy Incubator na przedmiot." },
  { d:0, b:false, en:"Trinkets that had a chance to receive additional Legion items when opening a Reward Chest in a Heist instead now grant a chance to receive additional Gold.", pl:"Trinkets, które dawały szansę na dodatkowe przedmioty Legion przy otwieraniu Reward Chest w Heist, dają teraz zamiast tego szansę na dodatkowe Gold (złoto)." },
  { d:0, b:false, en:"The Stash Tab Affinity for Incubators has been removed.", pl:"Usunięto Stash Tab Affinity dla Incubators." },
  { d:0, b:false, en:"Timeless Splinters can no longer drop outside of Legion encounters and Maps completed by Kingsmarch Atlas Runners.", pl:"Timeless Splinters nie mogą już wypadać poza spotkaniami Legion oraz Mapami ukończonymi przez Kingsmarch Atlas Runners." },
  { d:0, b:false, en:"The Heist Rogue Equipment modifiers for Heist Chests have a chance to duplicate contained Timeless Splinters can no longer roll.", pl:"Modyfikatory Heist Rogue Equipment dla Heist Chests, dające szansę na duplikację zawartych Timeless Splinters, nie mogą się już wylosować." },
  { d:0, b:false, en:"Legion Generals now drop more Timeless Splinters on average.", pl:"Legion Generals upuszczają teraz średnio więcej Timeless Splinters." },
  { d:0, b:false, en:"Non-Sergeant, non-General Legion Monsters no longer drop Timeless Splinters.", pl:"Potwory Legion inne niż Sergeants i Generals nie upuszczają już Timeless Splinters." },
  { d:0, b:false, en:"Sergeants and Chests now have a lower chance to drop Timeless Splinters, but now drop them in higher stack sizes.", pl:"Sergeants i Chests mają teraz mniejszą szansę na upuszczenie Timeless Splinters, ale upuszczają je w większych stosach." },
  { d:0, b:false, en:"Lowered the effect of Map Item Quantity on the chances for Sergeants and Chests to drop Timeless Splinters.", pl:"Zmniejszono wpływ Map Item Quantity na szanse Sergeants i Chests na upuszczenie Timeless Splinters." },
  { d:0, b:false, en:"The Emblematic Atlas Passive Skill now grants 0.3% chance for Timeless Splinters to drop as Timeless Emblems instead in your Maps (previously 0.6%), and the small Passive preceding it now grants 10% increased Quantity of Timeless Splinters dropped by Legion Generals in your Maps.", pl:"Pasywna umiejętność Atlasu Emblematic nadaje teraz 0,3% szansy, że Timeless Splinters wypadną zamiast tego jako Timeless Emblems na twoich Mapach (poprzednio 0,6%), a poprzedzający ją mały Passive nadaje teraz 10% zwiększonej Quantity of Timeless Splinters upuszczanych przez Legion Generals na twoich Mapach." },
  { d:0, b:false, en:"The small Passive Skills in the Logistical Support and Pillaged Treasures cluster no longer provide Chest or Monster Duplicate Splinter chance.", pl:"Małe pasywne umiejętności w klastrach Logistical Support i Pillaged Treasures nie zapewniają już szansy na duplikację Splinter z Chest ani Monster." }
]});
PN({ id: "gem-socket-changes", title: { pl: "Zmiany w slotach na gemy", en: "Gem Socket Changes" }, lines: [
  { d:0, b:false, en:"Gems can now be Socketed into any Equipment Socket, even if the Gem Colour does not match the Socket Colour.", pl:"Gemy można teraz włożyć w dowolny Equipment Socket, nawet jeśli Gem Colour (kolor gemu) nie pasuje do Socket Colour (koloru slotu)." },
  { d:0, b:false, en:"Socketed Gems now gain +10% to Quality in Red, Green, and Blue Sockets if the Gem colour matches the Socket colour.", pl:"Włożone gemy zyskują teraz +10% to Quality w Red, Green i Blue Sockets, jeśli kolor gemu pasuje do koloru slotu." },
  { d:0, b:false, en:"Item Sockets are now always White by default. Each Socket generated on an item has a small chance to roll as a Red, Green, or Blue Socket instead, and the selected colour will still be proportional to the attribute requirements of the item.", pl:"Sloty przedmiotów są teraz domyślnie zawsze White (białe). Każdy slot wygenerowany na przedmiocie ma niewielką szansę wylosować się zamiast tego jako Red, Green lub Blue Socket, a wybrany kolor wciąż jest proporcjonalny do wymagań atrybutów przedmiotu." },
  { d:0, b:false, en:"The chance for Sockets to roll as Red, Green, or Blue increases with higher item levels.", pl:"Szansa na wylosowanie slotów jako Red, Green lub Blue rośnie wraz z wyższym item level." },
  { d:0, b:false, en:"Chromatic Orbs and Tainted Chromatic Orbs now force one of the Sockets on the item to be Non-White, while the rest of the Sockets on the item will roll colours normally. Higher Quality on items increases the chance for Non-White Sockets to appear.", pl:"Chromatic Orbs oraz Tainted Chromatic Orbs wymuszają teraz, by jeden ze slotów przedmiotu był Non-White (nie-biały), podczas gdy pozostałe sloty losują kolory normalnie. Wyższa Quality na przedmiocie zwiększa szansę na pojawienie się Non-White Sockets." },
  { d:0, b:false, en:"Currency that adds Sockets to items such as Jeweller's Orbs, Tainted Jeweller's Orbs and Orbs of Binding will always generate the added sockets as White. This includes adding sockets through the Crafting Bench.", pl:"Waluty dodające sloty do przedmiotów, takie jak Jeweller's Orbs, Tainted Jeweller's Orbs i Orbs of Binding, zawsze generują dodane sloty jako White. Dotyczy to również dodawania slotów przez Crafting Bench." },
  { d:0, b:false, en:"As a result of these changes, Chromatic Orbs are now rarer, and are no longer sold by vendors in towns in exchange for Jeweller's Orbs. The Gold fees for Chromatic Orbs have also been increased for the Currency Exchange.", pl:"W wyniku tych zmian Chromatic Orbs są teraz rzadsze i nie są już sprzedawane przez vendorów w miastach w zamian za Jeweller's Orbs. Zwiększono również opłaty w Gold za Chromatic Orbs w Currency Exchange." },
  { d:0, b:false, en:"The Corruption outcome from Vaal Orbs that changes a Socket on a piece of Equipment to a White Socket has been removed. This outcome instead now turns a random White Socket on the item to be a Non-White Socket.", pl:"Usunięto wynik Corruption z Vaal Orbs, który zmieniał slot na przedmiocie w White Socket. Zamiast tego ten wynik zmienia teraz losowy White Socket na przedmiocie w Non-White Socket." },
  { d:0, b:false, en:"The Corruption outcome from the Locus of Corruption that turns all Sockets White on a piece of Equipment has been removed. This outcome instead now turns all White Sockets on the item to be Non-White.", pl:"Usunięto wynik Corruption z Locus of Corruption, który zmieniał wszystkie sloty przedmiotu na White. Zamiast tego ten wynik zmienia teraz wszystkie White Sockets na przedmiocie na Non-White." },
  { d:0, b:false, en:"Trinkets Modifiers for a chance of Chromatic Orbs to drop as Jeweller's Orbs or Orbs of Fusing in Heists can no longer roll.", pl:"Modyfikatory Trinkets dające szansę, że Chromatic Orbs wypadną jako Jeweller's Orbs lub Orbs of Fusing w Heist, nie mogą się już wylosować." },
  { d:0, b:false, en:"Added new Trinket modifiers for a chance of Jeweller's Orbs or Orbs of Fusing to drop as Chromatic Orbs in Heists.", pl:"Dodano nowe modyfikatory Trinket dające szansę, że Jeweller's Orbs lub Orbs of Fusing wypadną jako Chromatic Orbs w Heist." },
  { d:0, b:false, en:"The Bestiary crafting option to create a Stack of 8 Chromatic Orbs instead now creates a Rare Four-Linked Helmet.", pl:"Opcja craftu Bestiary tworząca stos 8 Chromatic Orbs tworzy teraz zamiast tego Rare Four-Linked Helmet (rzadki hełm z czterema linkami)." },
  { d:0, b:false, en:"Added the following new Crafting Bench options that modify Socket colours:", pl:"Dodano następujące nowe opcje Crafting Bench modyfikujące kolory slotów:" },
  { d:1, b:false, en:"At Least Two Non-White Sockets (cost 5 Chromatic Orbs).", pl:"At Least Two Non-White Sockets — co najmniej dwa nie-białe sloty (koszt 5 Chromatic Orbs)." },
  { d:1, b:false, en:"At Least Three Non-White Sockets (cost 20 Chromatic Orbs).", pl:"At Least Three Non-White Sockets — co najmniej trzy nie-białe sloty (koszt 20 Chromatic Orbs)." },
  { d:1, b:false, en:"At Least Four Non-White Sockets (cost 75 Chromatic Orbs).", pl:"At Least Four Non-White Sockets — co najmniej cztery nie-białe sloty (koszt 75 Chromatic Orbs)." },
  { d:0, b:false, en:"The Crafting Bench options for Red, Green and Blue Sockets have been removed.", pl:"Usunięto opcje Crafting Bench dla Red, Green i Blue Sockets." },
  { d:0, b:false, en:"The Horticrafting Station option to Reforge the colour of a random socket on an item, turning it White has been removed.", pl:"Usunięto opcję Horticrafting Station przekuwającą kolor losowego slotu na przedmiocie na White." },
  { d:0, b:false, en:"The following Unique items now have a hidden property on them preventing them from having White Sockets: Dialla's Malefaction, Skin of the Lords, and Skin of the Loyal. Existing versions of these Uniques are not affected by this change.", pl:"Następujące przedmioty Unique mają teraz ukrytą właściwość uniemożliwiającą posiadanie White Sockets: Dialla's Malefaction, Skin of the Lords oraz Skin of the Loyal. Istniejące wersje tych Unique nie są objęte tą zmianą." },
  { d:0, b:false, en:"The Dialla's Malefaction Unique Body Armour now has Gems Socketed always have the Quality bonus from Socket Colour. It no longer has Gems can be Socketed in this Item ignoring Socket Colour, as this is now the default behaviour. This change affects existing versions of this Unique. It now also has Gems Socketed in Green Sockets have +20% to Quality (previously +30%). You can update existing versions of this item to the new, worse values with a Divine Orb, if you feel so inclined.", pl:"Unikatowy Body Armour Dialla's Malefaction ma teraz: włożone gemy zawsze mają bonus Quality od Socket Colour. Nie ma już „Gems can be Socketed in this Item ignoring Socket Colour\", ponieważ jest to teraz zachowanie domyślne. Ta zmiana dotyczy istniejących wersji tego Unique. Ma teraz również: gemy włożone w Green Sockets mają +20% to Quality (poprzednio +30%). Istniejące wersje możesz zaktualizować do nowych, gorszych wartości za pomocą Divine Orb, jeśli masz ochotę." },
  { d:0, b:false, en:"The Pariah Unique Ring now has +100-200 to Maximum Life per Red Socket, +100-200 to Maximum Mana per Green Socket, and +100-200 to Maximum Energy Shield per Blue Socket (all previously +100). Existing versions of this Unique can be updated to the new values with a Divine Orb.", pl:"Unikatowy pierścień Pariah ma teraz +100–200 to Maximum Life za każdy Red Socket, +100–200 to Maximum Mana za każdy Green Socket i +100–200 to Maximum Energy Shield za każdy Blue Socket (wszystkie poprzednio +100). Istniejące wersje tego Unique można zaktualizować do nowych wartości za pomocą Divine Orb." },
  { d:0, b:false, en:"The Prismatic Eclipse Unique Sword now has 25-35% increased Global Physical Damage per Red Socket (previously 25% increased Global Physical Damage with Weapons per Red Socket), 10-14% increased Global Attack Speed per Green Socket (previously 12%), and 0.6-0.8% of Physical Attack Damage Leeched as Mana per Blue Socket (previously 0.4%). It also now has +0.2-0.3 metres to Melee Strike Range per White Socket (previously +0.2). Existing items can be updated to the new values using a Divine Orb.", pl:"Unikatowy miecz Prismatic Eclipse ma teraz 25–35% increased Global Physical Damage za każdy Red Socket (poprzednio 25% increased Global Physical Damage with Weapons za każdy Red Socket), 10–14% increased Global Attack Speed za każdy Green Socket (poprzednio 12%) oraz 0,6–0,8% of Physical Attack Damage Leeched as Mana za każdy Blue Socket (poprzednio 0,4%). Ma też teraz +0,2–0,3 metra to Melee Strike Range za każdy White Socket (poprzednio +0,2). Istniejące przedmioty można zaktualizować do nowych wartości za pomocą Divine Orb." },
  { d:0, b:false, en:"The Scaeva Unique Sword no longer have Physical Attack Damage Leeched as Life per Red Socket, Physical Attack Damage Leeched as Mana per Blue Socket, increased Global Defences per White Socket, or increased Global Critical Strike Chance when in Main Hand. It instead now has 8-12% increased Area of Effect per Red Socket, 20-30% increased Global Critical Strike Chance per Blue Socket, and 6-8% increased Global Defences per Empty Socket. These changes do not affect existing versions of this Unique. In addition, it now has +10-15% Chance to Block Attack Damage when in Off Hand (previously +8%), +10-15% to Global Critical Strike Multiplier per Green Socket (previously +10%), and 30-50% increased Critical Strike Chance (previously 15-25%). A Divine Orb can be used on existing items to update them to these new values.", pl:"Unikatowy miecz Scaeva nie ma już Physical Attack Damage Leeched as Life za każdy Red Socket, Physical Attack Damage Leeched as Mana za każdy Blue Socket, increased Global Defences za każdy White Socket ani increased Global Critical Strike Chance, gdy jest w Main Hand. Zamiast tego ma teraz 8–12% increased Area of Effect za każdy Red Socket, 20–30% increased Global Critical Strike Chance za każdy Blue Socket oraz 6–8% increased Global Defences za każdy Empty Socket. Te zmiany nie dotyczą istniejących wersji tego Unique. Dodatkowo ma teraz +10–15% Chance to Block Attack Damage, gdy jest w Off Hand (poprzednio +8%), +10–15% to Global Critical Strike Multiplier za każdy Green Socket (poprzednio +10%) oraz 30–50% increased Critical Strike Chance (poprzednio 15–25%). Na istniejących przedmiotach można użyć Divine Orb, aby zaktualizować je do tych nowych wartości." },
  { d:0, b:false, en:"The Triad Grip Unique Gloves now have the following modifiers: Minions convert 25% of Physical Damage to Fire Damage per Socketed Red Gem (previously per Red Socket), Minions convert 25% of Physical Damage to Cold Damage per Socketed Green Gem (previously per Green Socket), Minions convert 25% of Physical Damage to Lightning Damage per Socketed Blue Gem (previously per Blue Socket), and Minions convert 25% of Physical Damage to Chaos Damage per Empty Socket (previously per White Socket). These changes do not affect existing versions of this Unique.", pl:"Unikatowe rękawice Triad Grip mają teraz następujące modyfikatory: Minions convert 25% of Physical Damage to Fire Damage za każdy Socketed Red Gem (poprzednio za każdy Red Socket), Minions convert 25% of Physical Damage to Cold Damage za każdy Socketed Green Gem (poprzednio za każdy Green Socket), Minions convert 25% of Physical Damage to Lightning Damage za każdy Socketed Blue Gem (poprzednio za każdy Blue Socket) oraz Minions convert 25% of Physical Damage to Chaos Damage za każdy Empty Socket (poprzednio za każdy White Socket). Te zmiany nie dotyczą istniejących wersji tego Unique." },
  { d:0, b:false, en:"The Untouched Soul Unique Amulet now has +12% to all Elemental Resistances for each Empty White Socket on any Equipped Item (previously +18%). Existing items can be made worse with a Divine Orb.", pl:"Unikatowy amulet Untouched Soul ma teraz +12% to all Elemental Resistances za każdy Empty White Socket na dowolnym założonym przedmiocie (poprzednio +18%). Istniejące przedmioty można pogorszyć za pomocą Divine Orb." },
  { d:0, b:false, en:"The Bow Passive Mastery that provided +100 to Accuracy Rating per Green Socket on Equipped Bow has been replaced with 20% increased bonuses gained from Equipped Quiver.", pl:"Passive Mastery dla Bow, która dawała +100 to Accuracy Rating za każdy Green Socket na założonym Bow, została zastąpiona przez 20% increased bonuses gained from Equipped Quiver." },
  { d:0, b:false, en:"The Staff Passive Mastery that provided 3% increased Maximum Life per Red Socket on Equipped Staff and 5% increased Maximum Mana per Blue Socket on equipped Staff has been replaced with 12% increased Maximum Life and Mana if your equipped Staff has a Red and Blue Socket.", pl:"Passive Mastery dla Staff, która dawała 3% increased Maximum Life za każdy Red Socket na założonym Staff i 5% increased Maximum Mana za każdy Blue Socket na założonym Staff, została zastąpiona przez 12% increased Maximum Life and Mana, jeśli twój założony Staff ma Red i Blue Socket." },
  { d:0, b:false, en:"The Two Hand Passive Mastery that provided 10% increased Armour per Red Socket on Main Hand Weapon and 10% increased Evasion Rating per Green Socket on Main Hand Weapon has been replaced with 30% increased Armour and Evasion Rating if your Main Hand Weapon has a Red and Green Socket.", pl:"Passive Mastery dla Two Hand, która dawała 10% increased Armour za każdy Red Socket na broni w Main Hand i 10% increased Evasion Rating za każdy Green Socket na broni w Main Hand, została zastąpiona przez 30% increased Armour and Evasion Rating, jeśli twoja broń w Main Hand ma Red i Green Socket." },
  { d:0, b:false, en:"Enchantments on Body Armour and Weapons related to White Sockets or those that set all Sockets to be Blue, Green or Red no longer appear on Heist Rewards or from Tailoring and Tempering Orbs.", pl:"Enchanty na Body Armour i Weapons związane z White Sockets lub ustawiające wszystkie sloty na Blue, Green albo Red nie pojawiają się już w Heist Rewards ani z Tailoring i Tempering Orbs." },
  { d:0, b:false, en:"The Omen of Blanching has been renamed to Omen of Trichromatism. It now will be Consumed when you use a Chromatic Orb on an item to guarantee at least one Red, Green and Blue Socket.", pl:"Omen of Blanching zmienił nazwę na Omen of Trichromatism. Zostaje teraz zużyty, gdy użyjesz Chromatic Orb na przedmiocie, aby zagwarantować co najmniej jeden Red, Green i Blue Socket." },
  { d:0, b:false, en:"Vorici's Fortification Safehouse rewards have also been adjusted. At Rank 1, the reward is a bench that reforges the number of Sockets on an item 100 times, using the outcome with the greatest number of Sockets (previously colours of Sockets). At Rank 2, the reward is a bench that reforges the colours of Sockets on an item 25 times, using the outcome with the greatest number of Non-White Socket colours (previously number of Sockets).", pl:"Dostosowano również nagrody Safehouse Vorici's Fortification. Na Rank 1 nagrodą jest bench, który przekuwa liczbę slotów na przedmiocie 100 razy, wybierając wynik z największą liczbą slotów (poprzednio kolorów slotów). Na Rank 2 nagrodą jest bench, który przekuwa kolory slotów na przedmiocie 25 razy, wybierając wynik z największą liczbą kolorów Non-White Socket (poprzednio liczbą slotów)." }
]});

PN({ id: "talisman-revamp", title: { pl: "Przebudowa Talismans", en: "Talisman Revamp" }, lines: [
  { d:0, b:false, en:"Talismans have been long-neglected, and have lacked a meaningful place or purpose in Path of Exile. With this update we've made a number of changes to bring Talismans back to relevance.", pl:"Talismans były długo zaniedbywane i brakowało im sensownego miejsca oraz celu w Path of Exile. W tej aktualizacji wprowadziliśmy szereg zmian, które przywracają Talismans znaczenie." },
  { d:0, b:false, en:"Talismans now have special Enchantment Modifiers, rather than special Implicit Modifiers, and are no longer Corrupted by default. Talismans have a chance to drop from Red Beasts or Bestiary Bosses, and each Talisman is tied to a specific Beast.", pl:"Talismans mają teraz specjalne Enchantment Modifiers zamiast specjalnych Implicit Modifiers i nie są już domyślnie Corrupted. Talismans mają szansę wypaść z Red Beasts lub Bestiary Bosses, a każdy Talisman jest powiązany z konkretną Beast (bestią)." },
  { d:0, b:false, en:"Talismans cannot be Anointed, and their Enchantment Modifiers cannot be removed using the crafting bench option.", pl:"Talismans nie można Anoint (namaścić), a ich Enchantment Modifiers nie można usunąć opcją crafting bench." },
  { d:0, b:false, en:"Old Talisman base types are no longer obtainable, but will still exist in Standard.", pl:"Stare bazowe typy Talisman nie są już możliwe do zdobycia, ale nadal będą istnieć w Standard." },
  { d:0, b:false, en:"Non-Unique Talismans can no longer be obtained as rewards outside of Bestiary content, Divination Cards that grant Talismans, or Thane Jorgin's Betrayal Safehouse Rewards.", pl:"Nie-unikatowych Talismans nie można już zdobyć jako nagrody poza zawartością Bestiary, Divination Cards dającymi Talismans oraz nagrodami Safehouse Betrayal Thane'a Jorgina." },
  { d:0, b:false, en:"Thane Jorgin's Talisman Crafting Spree Betrayal Safehouse reward now offers regular Currency to craft the Talisman, instead of Tainted Currency.", pl:"Nagroda Safehouse Betrayal Thane'a Jorgina „Talisman Crafting Spree\" oferuje teraz zwykłą Currency do craftu Talisman, zamiast Tainted Currency." },
  { d:0, b:false, en:"Unique Talismans are no longer in the core drop pool. They instead now have a chance to drop from Bestiary Bosses or from a new Beast-crafting recipe to create a new Talisman, which requires The Black Mórrigan beast to craft.", pl:"Unikatowe Talismans nie są już w podstawowej puli dropu. Zamiast tego mają teraz szansę wypaść z Bestiary Bosses lub z nowej receptury Beast-crafting tworzącej nowy Talisman, która do craftu wymaga bestii The Black Mórrigan." },
  { d:0, b:false, en:"The Blightwell Unique Talisman is now found on the Shield Crab Talisman base type (previously Clutching Talisman). It now has +50-100 to maximum Energy Shield (previously +20-30), and 10-15% increased Flask Effect Duration. Existing versions of this Unique are unaffected by these changes.", pl:"Unikatowy Talisman Blightwell występuje teraz na bazie Shield Crab Talisman (poprzednio Clutching Talisman). Ma teraz +50–100 to maximum Energy Shield (poprzednio +20–30) oraz 10–15% increased Flask Effect Duration. Istniejące wersje tego Unique nie są objęte tymi zmianami." },
  { d:0, b:false, en:"The Eyes of the Greatwolf Unique Talisman now generates with two random Enchantment Modifiers from other Talisman base types. It now has 50-100% increased Enchantment Modifier magnitudes (instead of Implicit Modifier magnitudes are doubled). These changes do not affect existing versions of the item.", pl:"Unikatowy Talisman Eyes of the Greatwolf generuje się teraz z dwoma losowymi Enchantment Modifiers z innych bazowych typów Talisman. Ma teraz 50–100% increased Enchantment Modifier magnitudes (zamiast „Implicit Modifier magnitudes are doubled\"). Te zmiany nie dotyczą istniejących wersji przedmiotu." },
  { d:0, b:false, en:"The Natural Hierarchy Unique Talisman is now found on the Rhex Talisman base type (previously Rotfeather Talisman), and no longer has increased Damage for each specific Damage type. Instead, it now grants Gain 10-15% of Physical Damage as Extra Lightning Damage, Gain 15-20% of Lightning Damage as Extra Cold Damage, Gain 20-25% of Cold Damage as Extra Fire Damage, and Gain 25-30% of Fire Damage as Extra Chaos Damage. Existing versions of this Unique are unaffected by these changes.", pl:"Unikatowy Talisman Natural Hierarchy występuje teraz na bazie Rhex Talisman (poprzednio Rotfeather Talisman) i nie ma już increased Damage dla każdego konkretnego typu obrażeń. Zamiast tego daje teraz: Gain 10–15% of Physical Damage as Extra Lightning Damage, Gain 15–20% of Lightning Damage as Extra Cold Damage, Gain 20–25% of Cold Damage as Extra Fire Damage oraz Gain 25–30% of Fire Damage as Extra Chaos Damage. Istniejące wersje tego Unique nie są objęte tymi zmianami." },
  { d:0, b:false, en:"The Rigwald's Curse Unique Talisman is now found on the Wolf Alpha Talisman base type (previously Wereclaw Talisman). It now has +5-10% to Unarmed Melee Attack Critical Strike Chance (previously +7%). Existing versions of this Unique are unaffected by these changes.", pl:"Unikatowy Talisman Rigwald's Curse występuje teraz na bazie Wolf Alpha Talisman (poprzednio Wereclaw Talisman). Ma teraz +5–10% to Unarmed Melee Attack Critical Strike Chance (poprzednio +7%). Istniejące wersje tego Unique nie są objęte tymi zmianami." },
  { d:0, b:false, en:"Bestiary Boss area levels will now match the level of the Red Beast used in the Blood Altar to create the portals.", pl:"Poziomy obszarów Bestiary Boss będą teraz odpowiadać poziomowi Red Beast użytej w Blood Altar do stworzenia portali." },
  { d:0, b:false, en:"In general, all Bestiary Bosses will now have greater Life than before, which is more comparative to the Life values on Bosses from other League mechanics.", pl:"Ogólnie wszystkie Bestiary Bosses będą teraz miały więcej Life niż wcześniej, co jest bardziej porównywalne z wartościami Life bossów z innych mechanik lig." },
  { d:0, b:false, en:"The specific Body Armour Unique items from each Bestiary Boss will now only drop if the area level is 80 or higher.", pl:"Konkretne unikatowe Body Armour z każdej Bestiary Boss wypadną teraz tylko, jeśli poziom obszaru wynosi 80 lub więcej." },
  { d:0, b:false, en:"The Bestiary craft to create a Rare Talisman has been replaced with a craft that Rerolls a Talisman base type, keeping the same Implicit and Explicit Modifiers.", pl:"Craft Bestiary tworzący Rare Talisman został zastąpiony craftem, który przelosowuje bazowy typ Talisman, zachowując te same Implicit i Explicit Modifiers." },
  { d:0, b:false, en:"The Bestiary craft to Transform an item from an Amulet into a Talisman has been replaced with a craft that creates an Imprint of a Rare Talisman.", pl:"Craft Bestiary przekształcający przedmiot z Amulet w Talisman został zastąpiony craftem, który tworzy Imprint (odcisk) Rare Talisman." },
  { d:0, b:false, en:"The Primal Delirium Orb is no longer obtainable, but existing ones will still function in Standard Leagues.", pl:"Primal Delirium Orb nie jest już możliwy do zdobycia, ale istniejące będą nadal działać w ligach Standard." },
  { d:0, b:false, en:"Trinkets that had a chance to receive additional Talisman items when opening a Reward Chest in a Heist instead now grant a chance to receive additional Gold.", pl:"Trinkets, które dawały szansę na dodatkowe przedmioty Talisman przy otwieraniu Reward Chest w Heist, dają teraz zamiast tego szansę na dodatkowe Gold." },
  { d:0, b:false, en:"The Craicic Chimeral Beast has been renamed to Craicic Croaker, which is a much more fitting name for a Gem Frog.", pl:"Bestia Craicic Chimeral zmieniła nazwę na Craicic Croaker, co jest znacznie trafniejszą nazwą dla Gem Frog (żaby-gema)." }
]});

PN({ id: "league-changes", title: { pl: "Zmiany w ligach (mechanikach)", en: "League Changes" }, lines: [
  { d:0, b:false, en:"After completing a Ritual Altar encounter, locusts will now point the way to the next Altar.", pl:"Po ukończeniu spotkania Ritual Altar szarańcze wskażą teraz drogę do następnego Altar." },
  { d:0, b:false, en:"When in The Forbidden Sanctum, Flask Charges are now restored when you interact with the Sanctum Map between each room. This does not apply to The Writhing Jar Unique Flask.", pl:"W The Forbidden Sanctum ładunki flasek (Flask Charges) są teraz uzupełniane, gdy wejdziesz w interakcję z Sanctum Map między pokojami. Nie dotyczy to unikatowej flaski The Writhing Jar." },
  { d:0, b:false, en:"Volatile Vaal Orbs can now be obtained as Sanctum Rewards.", pl:"Volatile Vaal Orbs można teraz zdobyć jako Sanctum Rewards." },
  { d:0, b:false, en:"Ultimatum is now the exclusive source of Catalysts. As a result, they have been removed from the following:", pl:"Ultimatum jest teraz wyłącznym źródłem Catalysts. W związku z tym zostały one usunięte z następujących miejsc:" },
  { d:1, b:false, en:"Ultimatum Rewards from Demolition in Heist have been replaced by Map Rewards.", pl:"Nagrody Ultimatum z Demolition w Heist zostały zastąpione przez Map Rewards." },
  { d:1, b:false, en:"Catalyst chests can no longer appear in Expedition, and Tujen no longer offers Catalysts from his shop.", pl:"Skrzynie z Catalyst nie mogą już pojawiać się w Expedition, a Tujen nie oferuje już Catalysts w swoim sklepie." },
  { d:1, b:false, en:"Catalysts can no longer be found as Ritual Reward Favours.", pl:"Catalysts nie można już znaleźć jako Ritual Reward Favours." },
  { d:0, b:false, en:"While channelling Verisium Ore you now cannot be damaged or stunned.", pl:"Podczas kanałowania Verisium Ore nie możesz teraz otrzymywać obrażeń ani zostać stunned (ogłuszony)." }
]});

PN({ id: "betrayal", title: { pl: "Betrayal", en: "Betrayal" }, lines: [
  { d:0, b:false, en:"Syndicate Leaders can no longer drop Allflame Embers. The Syndicate Mastermind can now only drop The Allflame Ember of Kulemak.", pl:"Syndicate Leaders nie mogą już upuszczać Allflame Embers. Syndicate Mastermind może teraz upuścić wyłącznie The Allflame Ember of Kulemak." },
  { d:0, b:false, en:"The average number of Scarabs dropped from Scarab Chests in Betrayal Safehouses has been doubled.", pl:"Średnia liczba Scarabs upuszczanych ze Scarab Chests w Betrayal Safehouses została podwojona." },
  { d:0, b:false, en:"Trapped Stashes in Betrayal Safehouses now have a time limit of 15 seconds (previously 10).", pl:"Trapped Stashes w Betrayal Safehouses mają teraz limit czasu 15 sekund (poprzednio 10)." },
  { d:0, b:false, en:"Cluster Jewels from Trapped Stashes and Crafting Sprees in Safehouses have a maximum item level of 83.", pl:"Cluster Jewels z Trapped Stashes i Crafting Sprees w Safehouses mają maksymalny item level 83." },
  { d:0, b:false, en:"Vagan's Fortification Safehouse Reward is now a Trapped Stash with Enshrouded Uniques. This does not apply to Ruthless.", pl:"Nagroda Safehouse Vagan's Fortification to teraz Trapped Stash z Enshrouded Uniques. Nie dotyczy to Ruthless." },
  { d:0, b:false, en:"Vagan's Transportation Safehouse Reward is now a chest containing Trarthan Scarabs.", pl:"Nagroda Safehouse Vagan's Transportation to teraz skrzynia zawierająca Trarthan Scarabs." }
]});
PN({ id: "breach", title: { pl: "Breach", en: "Breach" }, lines: [
  { d:0, b:false, en:"The average number of Monsters in Breach Monster packs has been reduced.", pl:"Średnia liczba potworów w Breach Monster packs (grupach potworów Breach) została zmniejszona." },
  { d:0, b:false, en:"The number of Monster packs spawned in Unstable Breaches has been reduced by 25%. The progress for killing Breach Monsters has been increased by 17% to compensate for the reduced number of Monsters.", pl:"Liczba grup potworów pojawiających się w Unstable Breaches została zmniejszona o 25%. Postęp za zabijanie Breach Monsters zwiększono o 17%, aby zrekompensować mniejszą liczbę potworów." },
  { d:0, b:false, en:"The maximum number of Unstable Breaches that can be open at once has been reduced to 2 (previously 3).", pl:"Maksymalna liczba Unstable Breaches otwartych jednocześnie została zmniejszona do 2 (poprzednio 3)." },
  { d:0, b:false, en:"The Swelling Ranks Atlas Passive Skill now grants Breach Monsters in your Maps have 10% increased Pack Size (previously 20%).", pl:"Pasywna umiejętność Atlasu Swelling Ranks nadaje teraz: Breach Monsters na twoich Mapach mają 10% increased Pack Size (poprzednio 20%)." },
  { d:0, b:false, en:"Small Passives that granted Breach Monsters in your Maps have 5% increased Pack Size instead now grant Breaches in your Maps spawn 5% increased Rare Monsters.", pl:"Małe pasywy, które dawały „Breach Monsters na twoich Mapach mają 5% increased Pack Size\", dają teraz zamiast tego „Breaches na twoich Mapach przywołują 5% increased Rare Monsters\"." },
  { d:0, b:false, en:"The Evolving Hives Atlas Passive Skill now grants Breaches in your Maps spawn 15% increased Rare and Magic Monsters (previously 25%).", pl:"Pasywna umiejętność Atlasu Evolving Hives nadaje teraz: Breaches na twoich Mapach przywołują 15% increased Rare and Magic Monsters (poprzednio 25%)." },
  { d:0, b:false, en:"Small Passives that granted Breaches in your Maps spawn 8% increased Magic Monsters now have values of 5%.", pl:"Małe pasywy, które dawały „Breaches na twoich Mapach przywołują 8% increased Magic Monsters\", mają teraz wartość 5%." },
  { d:0, b:false, en:"These changes do not affect the amount of Hiveblood or Wombgifts you receive.", pl:"Te zmiany nie wpływają na ilość Hiveblood ani Wombgifts, które otrzymujesz." },
  { d:0, b:false, en:"Equipment Items birthed by the Genesis Tree inherently have slightly less Modifier Tier Rating and bias towards higher tier base types. There is also a lower inherent chance to birth additional Equipment items.", pl:"Przedmioty Equipment zrodzone przez Genesis Tree mają wewnętrznie nieco niższy Modifier Tier Rating i skłaniają się ku bazom wyższego tieru. Jest też niższa wewnętrzna szansa na zrodzenie dodatkowych przedmiotów Equipment." },
  { d:0, b:false, en:"The maximum number of Equipment Genesis Tree Passive Points is now 16 (previously 20).", pl:"Maksymalna liczba punktów pasywnych Equipment Genesis Tree wynosi teraz 16 (poprzednio 20)." },
  { d:0, b:false, en:"Small Equipment Genesis Tree Passives that grant a chance for Wombgifts to Birth an additional Equipment Item now have values of 25% (previously 50%).", pl:"Małe pasywy Equipment Genesis Tree dające szansę, że Wombgifts zrodzą dodatkowy przedmiot Equipment, mają teraz wartość 25% (poprzednio 50%)." },
  { d:0, b:false, en:"Equipment Genesis Tree Notable Passives that grant increased chance for Modifiers of a specific type now have values of 300% (previously 500%).", pl:"Notable pasywy Equipment Genesis Tree dające zwiększoną szansę na modyfikatory konkretnego typu mają teraz wartość 300% (poprzednio 500%)." }
]});

PN({ id: "endgame-changes", title: { pl: "Zmiany w endgame", en: "Endgame Changes" }, lines: [
  { d:0, b:false, en:"Strange locations have begun to manifest on the Atlas, which Kirac has labelled as Anomalies.", pl:"Na Atlasie zaczęły manifestować się dziwne lokacje, które Kirac określił mianem Anomalies (anomalii)." },
  { d:0, b:false, en:"Upon completing Maps affected by a Voidstone, there is a chance that when you next open your Atlas an Anomaly may manifest. Atlas Anomalies do not require a Map item to enter.", pl:"Po ukończeniu Map objętych działaniem Voidstone istnieje szansa, że przy następnym otwarciu Atlasu zmanifestuje się Anomaly. Atlas Anomalies nie wymagają przedmiotu Map, aby do nich wejść." },
  { d:0, b:false, en:"Reflecting Mists and the Nameless Seer no longer randomly spawn within Maps, but instead now appear in their own Anomaly areas.", pl:"Reflecting Mists oraz Nameless Seer nie pojawiają się już losowo w Mapach, lecz zamiast tego występują we własnych obszarach Anomaly." },
  { d:0, b:false, en:"Atlas Anomalies are unaffected by your Atlas Passive Tree, and cannot be augmented using any Fragments, allowing them to be run at any time without feeling like they have to be saved for later to maximise potential rewards.", pl:"Atlas Anomalies nie są objęte twoim Atlas Passive Tree i nie można ich wzmocnić żadnymi Fragments, dzięki czemu można je robić w dowolnym momencie, bez poczucia, że trzeba je zachować na później, by zmaksymalizować potencjalne nagrody." },
  { d:0, b:false, en:"Reflect Map Modifiers have been reworked, instead of causing Monsters to Reflect a percentage of Physical or Elemental Hit Damage dealt to them, they instead cause Rare Monsters to have Physical or Elemental Thorns.", pl:"Modyfikatory Map typu Reflect zostały przebudowane — zamiast sprawiać, że potwory odbijają (Reflect) procent zadanych im Physical lub Elemental Hit Damage, sprawiają teraz, że Rare Monsters mają Physical lub Elemental Thorns." },
  { d:0, b:false, en:"Physical Thorns activates when Hit by Physical Damage and lasts for 5 seconds. While active, it reflects a fixed amount of Physical Damage each time the monster receives a Physical Hit. Monsters cannot gain Physical Thorns more than once every 10 seconds. You can only take Physical Thorns damage once every 0.1 seconds.", pl:"Physical Thorns aktywuje się, gdy potwór zostanie trafiony Physical Damage, i trwa 5 sekund. Gdy jest aktywne, odbija stałą ilość Physical Damage za każdym razem, gdy potwór otrzyma Physical Hit. Potwory nie mogą zyskać Physical Thorns częściej niż raz na 10 sekund. Obrażenia od Physical Thorns możesz otrzymać tylko raz na 0,1 sekundy." },
  { d:0, b:false, en:"Elemental Thorns activates when Hit by Elemental Damage and lasts for 5 seconds. While active, it reflects a fixed amount of Elemental Damage each time the monster receives an Elemental Hit, dealing Damage of the highest Elemental Damage type in the received Hit. Monsters cannot gain Elemental Thorns more than once every 10 seconds. You can only take Elemental Thorns damage once every 0.1 seconds.", pl:"Elemental Thorns aktywuje się, gdy potwór zostanie trafiony Elemental Damage, i trwa 5 sekund. Gdy jest aktywne, odbija stałą ilość Elemental Damage za każdym razem, gdy potwór otrzyma Elemental Hit, zadając obrażenia typu o najwyższym Elemental Damage w otrzymanym trafieniu. Potwory nie mogą zyskać Elemental Thorns częściej niż raz na 10 sekund. Obrażenia od Elemental Thorns możesz otrzymać tylko raz na 0,1 sekundy." },
  { d:0, b:false, en:"In Red Tier Maps, Rare Monsters have Physical Thorns reflecting 800 Physical Damage and Elemental Thorns reflecting 1500 Elemental Damage.", pl:"Na Mapach Red Tier Rare Monsters mają Physical Thorns odbijające 800 Physical Damage oraz Elemental Thorns odbijające 1500 Elemental Damage." },
  { d:0, b:false, en:"Reflected Damage from Thorns is able to be mitigated through Evasion, Block, Armour, Resistances, etc.", pl:"Odbite obrażenia od Thorns można redukować przez Evasion, Block, Armour, Resistances itp." },
  { d:0, b:false, en:"Reflect Modifiers no longer appear on Corrupted Side Areas in the Campaign.", pl:"Modyfikatory Reflect nie pojawiają się już w Corrupted Side Areas w kampanii." },
  { d:0, b:false, en:"The following Maps have been added back to the Atlas: Arachnid Nest, Basilica, Bazaar, Caldera, Cells, Channel, Colonnade, Colosseum, Conservatory, Crystal Ore, Desert, Desert Spring, Estuary, Forbidden Woods, Geode, Infested Valley, Laboratory, Malformation, Museum, Phantasmagoria, Pier, Plateau, Ramparts, Stagnation, Sunken City, Temple, Toxic Sewer, and Vault.", pl:"Następujące Mapy zostały ponownie dodane do Atlasu: Arachnid Nest, Basilica, Bazaar, Caldera, Cells, Channel, Colonnade, Colosseum, Conservatory, Crystal Ore, Desert, Desert Spring, Estuary, Forbidden Woods, Geode, Infested Valley, Laboratory, Malformation, Museum, Phantasmagoria, Pier, Plateau, Ramparts, Stagnation, Sunken City, Temple, Toxic Sewer oraz Vault." },
  { d:0, b:false, en:"The following Maps have been removed from the Atlas: Acid Caverns, Arena, Ashen Wood, Bog, Canyon, Carcass, Castle Ruins, Courtyard, Coves, Crimson Temple, Crimson Township, Cursed Crypt, Defiled Cathedral, Dig, Dry Sea, Dungeon, Lava Chamber, Lighthouse, Maze, Moon Temple, Mud Geyser, Necropolis, Pen, Racecourse, Sepulchre, Underground Sea, Wasteland, and Wharf.", pl:"Następujące Mapy zostały usunięte z Atlasu: Acid Caverns, Arena, Ashen Wood, Bog, Canyon, Carcass, Castle Ruins, Courtyard, Coves, Crimson Temple, Crimson Township, Cursed Crypt, Defiled Cathedral, Dig, Dry Sea, Dungeon, Lava Chamber, Lighthouse, Maze, Moon Temple, Mud Geyser, Necropolis, Pen, Racecourse, Sepulchre, Underground Sea, Wasteland oraz Wharf." },
  { d:0, b:false, en:"The Untainted Paradise Unique Map can no longer be obtained, and existing items cannot be used in Standard Leagues.", pl:"Unikatowa Mapa Untainted Paradise nie jest już możliwa do zdobycia, a istniejących przedmiotów nie można używać w ligach Standard." },
  { d:0, b:false, en:"Untainted Paradise can now be accessed through a randomly spawned event node on your Atlas, where it has received a few alterations to make it more difficult and rewarding...", pl:"Do Untainted Paradise można teraz dostać się przez losowo pojawiający się węzeł wydarzenia (event node) na Atlasie, gdzie otrzymała kilka zmian czyniących ją trudniejszą i bardziej opłacalną..." },
  { d:0, b:false, en:"The Decayed Voidstone socket on the Atlas now connects to the Forge of the Phoenix, Pit of the Chimera and Lair of the Hydra (in addition to the Maze of the Minotaur).", pl:"Slot Decayed Voidstone na Atlasie łączy się teraz z Forge of the Phoenix, Pit of the Chimera i Lair of the Hydra (oprócz Maze of the Minotaur)." },
  { d:0, b:false, en:"The Pit of the Chimera Boss now spawns only one wave of enemies per phase.", pl:"Boss Pit of the Chimera przywołuje teraz tylko jedną falę wrogów na fazę." },
  { d:0, b:false, en:"Memory Thread Maps now display which Map they will open.", pl:"Mapy Memory Thread pokazują teraz, którą Mapę otworzą." },
  { d:0, b:false, en:"The Enshrouded Astrolabe has been renamed to Deceptive Astrolabe.", pl:"Enshrouded Astrolabe zmienił nazwę na Deceptive Astrolabe." },
  { d:0, b:false, en:"Removed the item drop delay from versions of the Remembered and the Feared that can spawn in Maps, such as from the Horned Scarab of Awakening.", pl:"Usunięto opóźnienie wypadania przedmiotów z wersji the Remembered i the Feared, które mogą pojawiać się w Mapach, np. z Horned Scarab of Awakening." },
  { d:0, b:false, en:"Reduced the average amount of Modifier Effect applied to Explicit Modifiers when using a Reflecting Mist Currency on an item. This change does not affect the amount of Modifier Effect on Mirrored Jewellery found when interacting with a Reflecting Mist object.", pl:"Zmniejszono średnią ilość Modifier Effect nakładanego na Explicit Modifiers przy użyciu waluty Reflecting Mist na przedmiocie. Ta zmiana nie wpływa na ilość Modifier Effect na Mirrored Jewellery znajdowanej podczas interakcji z obiektem Reflecting Mist." },
  { d:0, b:false, en:"Reflecting Mist objects now have a much higher chance to drop a Reflecting Mist Currency item.", pl:"Obiekty Reflecting Mist mają teraz znacznie wyższą szansę na upuszczenie waluty Reflecting Mist." }
]});

PN({ id: "atlas-passive-tree-changes", title: { pl: "Zmiany w Atlas Passive Tree", en: "Atlas Passive Tree Changes" }, lines: [
  { d:0, b:false, en:"Added a new Altered Prophecy cluster to the Atlas Passive Tree. The Notable grants your Tier 14+ Maps 4% chance to drop a Scrying Orb on completion, while the small Passives grant your Maps increased chance to drop Divination Cards. In Ruthless, this cluster grants Scarab related bonuses.", pl:"Dodano nowy klaster Altered Prophecy do Atlas Passive Tree. Notable nadaje twoim Mapom Tier 14+ 4% szansy na upuszczenie Scrying Orb po ukończeniu, a małe pasywy dają twoim Mapom zwiększoną szansę na upuszczenie Divination Cards. W Ruthless ten klaster daje bonusy powiązane ze Scarab." },
  { d:0, b:false, en:"The Scrying Orb is a new currency item that stores the Map that the currency item was found in. It then allows you to Scry the Divination Cards of the Map area listed on the item to a Map on your Atlas.", pl:"Scrying Orb to nowy przedmiot waluty, który zapisuje Mapę, na której waluta została znaleziona. Pozwala następnie „przenieść\" (Scry) Divination Cards z obszaru Mapy wskazanego na przedmiocie na Mapę na twoim Atlasie." },
  { d:0, b:false, en:"The Brave the Tower Atlas Passive Skill now has Ultimatum Boss drops 10 of a random Catalyst (previously a full stack of a random Catalyst).", pl:"Pasywna umiejętność Atlasu Brave the Tower ma teraz: Ultimatum Boss upuszcza 10 losowego Catalyst (poprzednio pełny stos losowego Catalyst)." },
  { d:0, b:false, en:"The Dutiful Soldier Atlas Passive Skill now also grants Blueprints found in your Maps have a 15% chance to have a special Implicit.", pl:"Pasywna umiejętność Atlasu Dutiful Soldier nadaje teraz również: Blueprints znalezione na twoich Mapach mają 15% szansy na posiadanie specjalnego Implicit." }
]});

PN({ id: "player-changes", title: { pl: "Zmiany dla postaci (gracza)", en: "Player Changes" }, lines: [
  { d:0, b:false, en:"Sources of chance to Avoid all Damage from Hits are now additive with sources of Avoiding Damage of a specific Type from Hits. Some Damage Avoidance stat descriptions have been adjusted to better communicate these chances are additive with each other.", pl:"Źródła szansy na Avoid all Damage from Hits są teraz sumowane (additive) ze źródłami Avoiding Damage konkretnego typu from Hits. Niektóre opisy statystyk Damage Avoidance dostosowano, aby lepiej komunikować, że te szanse sumują się ze sobą." },
  { d:0, b:false, en:"Lowered the Life of various Monsters when used as Spectres. In general, no Spectre should have more life than a Meatsack. Some of the Monsters that have had their Life reduced include the Unholy Aberrations from the Unholy Trinity boss fight, Originator-Influenced Monsters, and Robot Monsters found in the hidden area in the Refinery.", pl:"Obniżono Life różnych potworów, gdy są używane jako Spectres. Ogólnie żaden Spectre nie powinien mieć więcej życia niż Meatsack. Do potworów, którym obniżono Life, należą m.in. Unholy Aberrations z walki z bossem Unholy Trinity, potwory Originator-Influenced oraz Robot Monsters z ukrytego obszaru w Refinery." },
  { d:0, b:false, en:"All Non-Spectre Minions no longer pause while attacking. Many Minions already didn't pause while attacking, and are unaffected by this change. This change will be a significant damage per second increase for the following Minion types in particular:", pl:"Wszystkie Minions inne niż Spectres nie zatrzymują się już podczas atakowania. Wiele Minions już wcześniej nie zatrzymywało się przy ataku i nie są objęte tą zmianą. Ta zmiana będzie znaczącym wzrostem damage per second szczególnie dla następujących typów Minions:" },
  { d:1, b:false, en:"Dominating Blow.", pl:"Dominating Blow." },
  { d:1, b:false, en:"Raised Zombies.", pl:"Raised Zombies." },
  { d:1, b:false, en:"Stone, Ice, Flame, Chaos and Lightning Golems.", pl:"Stone, Ice, Flame, Chaos i Lightning Golems." },
  { d:1, b:false, en:"Summoned Raging Spirits.", pl:"Summoned Raging Spirits." },
  { d:1, b:false, en:"Summoned Skeletons.", pl:"Summoned Skeletons." },
  { d:0, b:false, en:"Skills, Items and Modifiers that once stated that Increases and Reductions to Spell Damage also apply to Attack Damage have been replaced with the new Arcane Might Keyword. This is purely a desciptive change.", pl:"Umiejętności, przedmioty i modyfikatory, które dawniej mówiły, że „Increases and Reductions to Spell Damage also apply to Attack Damage\", zastąpiono nowym słowem kluczowym Arcane Might. To wyłącznie zmiana opisowa." }
]});

PN({ id: "ascendancy-changes", title: { pl: "Zmiany w Ascendancy", en: "Ascendancy Changes" }, lines: [
  { d:0, b:false, en:"The Deathmarked Notable Passive Skill no longer has Marked Enemy cannot Evade Attacks. It now has 10% increased Effect of your Marks per maximum Power Charge, and 3% of Leech is Instant per maximum Power Charge.", pl:"Notable pasyw Deathmarked nie ma już „Marked Enemy cannot Evade Attacks\". Ma teraz 10% increased Effect of your Marks za każdy maksymalny Power Charge oraz 3% of Leech is Instant za każdy maksymalny Power Charge." },
  { d:0, b:false, en:"The Mystical Infusion Notable Passive Skill no longer grants Base Spell Critical Strike Chance of Spells is equal to that of Main Hand Weapon. It now grants Spell Critical Strike Chance Bifurcates, and 30% less Spell Critical Strike Chance.", pl:"Notable pasyw Mystical Infusion nie daje już „Base Spell Critical Strike Chance of Spells is equal to that of Main Hand Weapon\". Daje teraz „Spell Critical Strike Chance Bifurcates\" oraz 30% less Spell Critical Strike Chance." },
  { d:0, b:false, en:"Bifurcated Critical Strikes cause Critical Strike chance to be rolled twice when determining if a Critical Strike should occur:", pl:"Bifurcated Critical Strikes sprawiają, że przy ustalaniu, czy nastąpi Critical Strike, szansa na Critical Strike jest losowana dwukrotnie:" },
  { d:1, b:false, en:"If either roll succeeds the hit will be a regular Critical Strike, and if both rolls succeed the amount of extra damage dealt by the critical strike will be doubled. This is equivalent to doubling the amount by which the Critical Strike Multiplier exceeds 100 for that Hit.", pl:"Jeśli powiedzie się którykolwiek rzut, trafienie będzie zwykłym Critical Strike; jeśli powiodą się oba rzuty, ilość dodatkowych obrażeń zadanych przez critical strike zostanie podwojona. Jest to równoważne podwojeniu wartości, o jaką Critical Strike Multiplier przekracza 100 dla tego trafienia." },
  { d:1, b:false, en:"If a modifier makes your Critical Strike Chance Lucky or Unlucky, that luck will apply individually to each of the critical strike chance rolls.", pl:"Jeśli modyfikator sprawia, że twoja Critical Strike Chance jest Lucky lub Unlucky, to „szczęście\" zastosuje się osobno do każdego z rzutów na szansę critical strike." },
  { d:1, b:false, en:"Effects which cause Hits to Always be Critical Strikes prevent Bifurcation - those hits do not roll the chance, so cannot roll it twice.", pl:"Efekty sprawiające, że trafienia są Always Critical Strikes, uniemożliwiają Bifurcation — takie trafienia nie losują szansy, więc nie mogą jej losować dwukrotnie." },
  { d:0, b:false, en:"The Ritual of Awakening Passive Skill now has 3% more Damage per Summoned Totem (preivously 5%).", pl:"Pasyw Ritual of Awakening ma teraz 3% more Damage za każdy Summoned Totem (poprzednio 5%)." },
  { d:0, b:false, en:"Added a new Instruments of Justice Notable Passive Skill which requires Instruments of Virtue. This Notable grants Base Spell Critical Strike Chance of Spells is equal to that of Main Hand Weapon.", pl:"Dodano nowy notable pasyw Instruments of Justice, który wymaga Instruments of Virtue. Ten Notable nadaje „Base Spell Critical Strike Chance of Spells is equal to that of Main Hand Weapon\"." },
  { d:0, b:false, en:"The Instruments of Zeal Notable Passive Skill now grants +3 to Maximum Fanatic Charges (previously +4). The Fanaticism Buff now lasts for 5 seconds (previously 4), and now grants 75% less Cost of Spells you cast yourself (previously 75% reduced).", pl:"Notable pasyw Instruments of Zeal nadaje teraz +3 to Maximum Fanatic Charges (poprzednio +4). Buff Fanaticism trwa teraz 5 sekund (poprzednio 4) i daje teraz 75% less Cost of Spells you cast yourself (poprzednio 75% reduced)." },
  { d:0, b:false, en:"Added a new Notable, Unhallowed Rite, which requires either Vile Bastion or Forbidden Power. Unhallowed Rite causes you to gain Spirit Infusion every second while Channelling a Spell. Each stack of Spirit Infusion grants 30% faster start of Energy Shield Recharge, Channelling Spells deal 10% more Damage and Channelling Spells have 20% more Cost. Maximum of 5 stacks. You lose one stack every 0.5 seconds if you have not gained a stack in the past 2 seconds.", pl:"Dodano nowy notable, Unhallowed Rite, który wymaga Vile Bastion albo Forbidden Power. Unhallowed Rite sprawia, że co sekundę zyskujesz Spirit Infusion podczas kanałowania zaklęcia. Każdy stack Spirit Infusion daje 30% faster start of Energy Shield Recharge; kanałowane zaklęcia zadają 10% more Damage i mają 20% more Cost. Maksymalnie 5 stacków. Tracisz jeden stack co 0,5 sekundy, jeśli nie zyskałeś stacka w ciągu ostatnich 2 sekund." },
  { d:0, b:false, en:"The Notables for the Reliquarian Ascendancy have been shuffled, below are the Passives available for Curse of the Allflame.", pl:"Notable dla Ascendancy Reliquarian zostały przetasowane; poniżej pasywy dostępne w Curse of the Allflame." }
]});

PN({ id: "passive-skill-tree-changes", title: { pl: "Zmiany w Passive Skill Tree", en: "Passive Skill Tree Changes" }, lines: [
  { d:0, b:false, en:"Added a new Arcane Conservation cluster to the north-east of the Witch's starting location. The Arcane Conservation Notable grants 10% increased Cast Speed, 20% increased Mana Cost Efficiency of Spells, and 3% increased Intelligence.", pl:"Dodano nowy klaster Arcane Conservation na północny wschód od miejsca startowego Witch. Notable Arcane Conservation daje 10% increased Cast Speed, 20% increased Mana Cost Efficiency of Spells oraz 3% increased Intelligence." },
  { d:0, b:false, en:"Added a new Contemplative Meditation cluster to the north-west of the Templar's starting location. The Contemplative Meditation Notable grants 8% increased Reservation Efficiency of Spells, and 20% increased Cost Efficiency.", pl:"Dodano nowy klaster Contemplative Meditation na północny zachód od miejsca startowego Templar. Notable Contemplative Meditation daje 8% increased Reservation Efficiency of Spells oraz 20% increased Cost Efficiency." },
  { d:0, b:false, en:"All sources of reduced Cost of Skills on the Passive Skill Tree have been converted to Cost Efficiency at appropriate values.", pl:"Wszystkie źródła reduced Cost of Skills na Passive Skill Tree przekonwertowano na Cost Efficiency o odpowiednich wartościach." },
  { d:0, b:false, en:"The Totem Passive Mastery option that grants increased Critical Strike Chance if you've Summoned a Totem Recently now has values of 40% (previously 60%).", pl:"Opcja Totem Passive Mastery, która daje increased Critical Strike Chance, jeśli Summoned a Totem Recently, ma teraz wartość 40% (poprzednio 60%)." },
  { d:0, b:false, en:"The Shaman's Dominion Notable Passive Skill now grants 50% increased Critical Strike Chance with Totem Skills (previously 60%), and the preceding small Passives now grant +16% to Critical Strike Multiplier with Totem Skills (previously 20%).", pl:"Notable pasyw Shaman's Dominion daje teraz 50% increased Critical Strike Chance with Totem Skills (poprzednio 60%), a poprzedzające małe pasywy dają teraz +16% to Critical Strike Multiplier with Totem Skills (poprzednio 20%)." }
]});
/* @@SECTIONS@@ */
